//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/util/LayerUtil.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapUtilLayerUtil")
#ifdef RESTRICT_OrgMapsforgeMapUtilLayerUtil
#define INCLUDE_ALL_OrgMapsforgeMapUtilLayerUtil 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapUtilLayerUtil 1
#endif
#undef RESTRICT_OrgMapsforgeMapUtilLayerUtil

#if !defined (OrgMapsforgeMapUtilLayerUtil_) && (INCLUDE_ALL_OrgMapsforgeMapUtilLayerUtil || defined(INCLUDE_OrgMapsforgeMapUtilLayerUtil))
#define OrgMapsforgeMapUtilLayerUtil_

@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelPoint;
@protocol JavaUtilList;
@protocol JavaUtilSet;

@interface OrgMapsforgeMapUtilLayerUtil : NSObject

#pragma mark Public

+ (id<JavaUtilList>)collisionFreeOrderedWithJavaUtilList:(id<JavaUtilList>)input;

+ (id<JavaUtilList>)getTilePositionsWithOrgMapsforgeCoreModelBoundingBox:(OrgMapsforgeCoreModelBoundingBox *)boundingBox
                                                                withByte:(jbyte)zoomLevel
                                          withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)topLeftPoint
                                                                 withInt:(jint)tileSize;

+ (id<JavaUtilSet>)getTilesWithOrgMapsforgeCoreModelBoundingBox:(OrgMapsforgeCoreModelBoundingBox *)boundingBox
                                                       withByte:(jbyte)zoomLevel
                                                        withInt:(jint)tileSize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapUtilLayerUtil)

FOUNDATION_EXPORT id<JavaUtilList> OrgMapsforgeMapUtilLayerUtil_getTilePositionsWithOrgMapsforgeCoreModelBoundingBox_withByte_withOrgMapsforgeCoreModelPoint_withInt_(OrgMapsforgeCoreModelBoundingBox *boundingBox, jbyte zoomLevel, OrgMapsforgeCoreModelPoint *topLeftPoint, jint tileSize);

FOUNDATION_EXPORT id<JavaUtilSet> OrgMapsforgeMapUtilLayerUtil_getTilesWithOrgMapsforgeCoreModelBoundingBox_withByte_withInt_(OrgMapsforgeCoreModelBoundingBox *boundingBox, jbyte zoomLevel, jint tileSize);

FOUNDATION_EXPORT id<JavaUtilList> OrgMapsforgeMapUtilLayerUtil_collisionFreeOrderedWithJavaUtilList_(id<JavaUtilList> input);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapUtilLayerUtil)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapUtilLayerUtil")
