//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/configuration/AnnotationEngine.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoConfigurationAnnotationEngine")
#ifdef RESTRICT_OrgMockitoConfigurationAnnotationEngine
#define INCLUDE_ALL_OrgMockitoConfigurationAnnotationEngine 0
#else
#define INCLUDE_ALL_OrgMockitoConfigurationAnnotationEngine 1
#endif
#undef RESTRICT_OrgMockitoConfigurationAnnotationEngine

#if !defined (OrgMockitoConfigurationAnnotationEngine_) && (INCLUDE_ALL_OrgMockitoConfigurationAnnotationEngine || defined(INCLUDE_OrgMockitoConfigurationAnnotationEngine))
#define OrgMockitoConfigurationAnnotationEngine_

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;

@protocol OrgMockitoConfigurationAnnotationEngine < JavaObject >

- (id)createMockForWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation
                           withJavaLangReflectField:(JavaLangReflectField *)field;

- (void)processWithIOSClass:(IOSClass *)clazz
                     withId:(id)testInstance;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoConfigurationAnnotationEngine)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoConfigurationAnnotationEngine)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoConfigurationAnnotationEngine")
