//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/hamcrest/Factory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgHamcrestFactory")
#ifdef RESTRICT_OrgHamcrestFactory
#define INCLUDE_ALL_OrgHamcrestFactory 0
#else
#define INCLUDE_ALL_OrgHamcrestFactory 1
#endif
#undef RESTRICT_OrgHamcrestFactory

#if !defined (OrgHamcrestFactory_) && (INCLUDE_ALL_OrgHamcrestFactory || defined(INCLUDE_OrgHamcrestFactory))
#define OrgHamcrestFactory_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol OrgHamcrestFactory < JavaLangAnnotationAnnotation >

@end

@interface OrgHamcrestFactory : NSObject < OrgHamcrestFactory >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgHamcrestFactory)

FOUNDATION_EXPORT id<OrgHamcrestFactory> create_OrgHamcrestFactory();

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgHamcrestFactory")
