//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/header/MapFileHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileHeader")
#ifdef RESTRICT_OrgMapsforgeMapReaderHeaderMapFileHeader
#define INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileHeader 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileHeader 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderHeaderMapFileHeader

#if !defined (OrgMapsforgeMapReaderHeaderMapFileHeader_) && (INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileHeader || defined(INCLUDE_OrgMapsforgeMapReaderHeaderMapFileHeader))
#define OrgMapsforgeMapReaderHeaderMapFileHeader_

@class OrgMapsforgeMapReaderHeaderMapFileInfo;
@class OrgMapsforgeMapReaderHeaderSubFileParameter;
@class OrgMapsforgeMapReaderReadBuffer;

@interface OrgMapsforgeMapReaderHeaderMapFileHeader : NSObject

#pragma mark Public

- (instancetype)init;

- (OrgMapsforgeMapReaderHeaderMapFileInfo *)getMapFileInfo;

- (jbyte)getQueryZoomLevelWithByte:(jbyte)zoomLevel;

- (OrgMapsforgeMapReaderHeaderSubFileParameter *)getSubFileParameterWithInt:(jint)queryZoomLevel;

- (void)readHeaderWithOrgMapsforgeMapReaderReadBuffer:(OrgMapsforgeMapReaderReadBuffer *)readBuffer
                                             withLong:(jlong)fileSize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderHeaderMapFileHeader)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderHeaderMapFileHeader_init(OrgMapsforgeMapReaderHeaderMapFileHeader *self);

FOUNDATION_EXPORT OrgMapsforgeMapReaderHeaderMapFileHeader *new_OrgMapsforgeMapReaderHeaderMapFileHeader_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderHeaderMapFileHeader *create_OrgMapsforgeMapReaderHeaderMapFileHeader_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderHeaderMapFileHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileHeader")
