//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/header/MapFileInfoBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder")
#ifdef RESTRICT_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder
#define INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder

#if !defined (OrgMapsforgeMapReaderHeaderMapFileInfoBuilder_) && (INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder || defined(INCLUDE_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder))
#define OrgMapsforgeMapReaderHeaderMapFileInfoBuilder_

@class IOSObjectArray;
@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeMapReaderHeaderMapFileInfo;
@class OrgMapsforgeMapReaderHeaderOptionalFields;

@interface OrgMapsforgeMapReaderHeaderMapFileInfoBuilder : NSObject {
 @public
  OrgMapsforgeCoreModelBoundingBox *boundingBox_;
  jlong fileSize_;
  jint fileVersion_;
  jlong mapDate_;
  jbyte numberOfSubFiles_;
  OrgMapsforgeMapReaderHeaderOptionalFields *optionalFields_;
  IOSObjectArray *poiTags_;
  NSString *projectionName_;
  jint tilePixelSize_;
  IOSObjectArray *wayTags_;
  jbyte zoomLevelMin_;
  jbyte zoomLevelMax_;
}

#pragma mark Package-Private

- (instancetype)init;

- (OrgMapsforgeMapReaderHeaderMapFileInfo *)build;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder, boundingBox_, OrgMapsforgeCoreModelBoundingBox *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder, optionalFields_, OrgMapsforgeMapReaderHeaderOptionalFields *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder, poiTags_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder, projectionName_, NSString *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder, wayTags_, IOSObjectArray *)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderHeaderMapFileInfoBuilder_init(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder *self);

FOUNDATION_EXPORT OrgMapsforgeMapReaderHeaderMapFileInfoBuilder *new_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderHeaderMapFileInfoBuilder *create_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderHeaderMapFileInfoBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderHeaderMapFileInfoBuilder")
