//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/junit/runners/model/FrameworkMember.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember")
#ifdef RESTRICT_OrgJunitRunnersModelFrameworkMember
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember 0
#else
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember 1
#endif
#undef RESTRICT_OrgJunitRunnersModelFrameworkMember

#if !defined (OrgJunitRunnersModelFrameworkMember_) && (INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember || defined(INCLUDE_OrgJunitRunnersModelFrameworkMember))
#define OrgJunitRunnersModelFrameworkMember_

@class IOSClass;
@class IOSObjectArray;
@protocol JavaUtilList;

@interface OrgJunitRunnersModelFrameworkMember : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)getName;

- (IOSClass *)getType;

- (jboolean)isPublic;

- (jboolean)isStatic;

#pragma mark Package-Private

- (IOSObjectArray *)getAnnotations;

- (jboolean)isShadowedByWithJavaUtilList:(id<JavaUtilList>)members;

- (jboolean)isShadowedByWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkMember *)otherMember;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelFrameworkMember)

FOUNDATION_EXPORT void OrgJunitRunnersModelFrameworkMember_init(OrgJunitRunnersModelFrameworkMember *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelFrameworkMember)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember")
