//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/junit/runners/model/FrameworkField.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkField")
#ifdef RESTRICT_OrgJunitRunnersModelFrameworkField
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkField 0
#else
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkField 1
#endif
#undef RESTRICT_OrgJunitRunnersModelFrameworkField

#if !defined (OrgJunitRunnersModelFrameworkField_) && (INCLUDE_ALL_OrgJunitRunnersModelFrameworkField || defined(INCLUDE_OrgJunitRunnersModelFrameworkField))
#define OrgJunitRunnersModelFrameworkField_

#define RESTRICT_OrgJunitRunnersModelFrameworkMember 1
#define INCLUDE_OrgJunitRunnersModelFrameworkMember 1
#include "org/junit/runners/model/FrameworkMember.h"

@class IOSClass;
@class IOSObjectArray;
@class JavaLangReflectField;

@interface OrgJunitRunnersModelFrameworkField : OrgJunitRunnersModelFrameworkMember

#pragma mark Public

- (id)getWithId:(id)target;

- (IOSObjectArray *)getAnnotations;

- (JavaLangReflectField *)getField;

- (NSString *)getName;

- (IOSClass *)getType;

- (jboolean)isPublic;

- (jboolean)isShadowedByWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkField *)otherMember;

- (jboolean)isStatic;

#pragma mark Package-Private

- (instancetype)initWithJavaLangReflectField:(JavaLangReflectField *)field;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelFrameworkField)

FOUNDATION_EXPORT void OrgJunitRunnersModelFrameworkField_initWithJavaLangReflectField_(OrgJunitRunnersModelFrameworkField *self, JavaLangReflectField *field);

FOUNDATION_EXPORT OrgJunitRunnersModelFrameworkField *new_OrgJunitRunnersModelFrameworkField_initWithJavaLangReflectField_(JavaLangReflectField *field) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitRunnersModelFrameworkField *create_OrgJunitRunnersModelFrameworkField_initWithJavaLangReflectField_(JavaLangReflectField *field);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelFrameworkField)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkField")
