//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/junit/runners/model/TestClass.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnersModelTestClass")
#ifdef RESTRICT_OrgJunitRunnersModelTestClass
#define INCLUDE_ALL_OrgJunitRunnersModelTestClass 0
#else
#define INCLUDE_ALL_OrgJunitRunnersModelTestClass 1
#endif
#undef RESTRICT_OrgJunitRunnersModelTestClass

#if !defined (OrgJunitRunnersModelTestClass_) && (INCLUDE_ALL_OrgJunitRunnersModelTestClass || defined(INCLUDE_OrgJunitRunnersModelTestClass))
#define OrgJunitRunnersModelTestClass_

@class IOSClass;
@class IOSObjectArray;
@class JavaLangReflectConstructor;
@protocol JavaUtilList;

@interface OrgJunitRunnersModelTestClass : NSObject

#pragma mark Public

- (instancetype)initWithIOSClass:(IOSClass *)klass;

- (id<JavaUtilList>)getAnnotatedFieldsWithIOSClass:(IOSClass *)annotationClass;

- (id<JavaUtilList>)getAnnotatedFieldValuesWithId:(id)test
                                     withIOSClass:(IOSClass *)annotationClass
                                     withIOSClass:(IOSClass *)valueClass;

- (id<JavaUtilList>)getAnnotatedMethodsWithIOSClass:(IOSClass *)annotationClass;

- (id<JavaUtilList>)getAnnotatedMethodValuesWithId:(id)test
                                      withIOSClass:(IOSClass *)annotationClass
                                      withIOSClass:(IOSClass *)valueClass;

- (IOSObjectArray *)getAnnotations;

- (IOSClass *)getJavaClass;

- (NSString *)getName;

- (JavaLangReflectConstructor *)getOnlyConstructor;

- (jboolean)isANonStaticInnerClass;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelTestClass)

FOUNDATION_EXPORT void OrgJunitRunnersModelTestClass_initWithIOSClass_(OrgJunitRunnersModelTestClass *self, IOSClass *klass);

FOUNDATION_EXPORT OrgJunitRunnersModelTestClass *new_OrgJunitRunnersModelTestClass_initWithIOSClass_(IOSClass *klass) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitRunnersModelTestClass *create_OrgJunitRunnersModelTestClass_initWithIOSClass_(IOSClass *klass);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelTestClass)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnersModelTestClass")
