//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/AdditionalAnswers.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoAdditionalAnswers")
#ifdef RESTRICT_OrgMockitoAdditionalAnswers
#define INCLUDE_ALL_OrgMockitoAdditionalAnswers 0
#else
#define INCLUDE_ALL_OrgMockitoAdditionalAnswers 1
#endif
#undef RESTRICT_OrgMockitoAdditionalAnswers

#if !defined (OrgMockitoAdditionalAnswers_) && (INCLUDE_ALL_OrgMockitoAdditionalAnswers || defined(INCLUDE_OrgMockitoAdditionalAnswers))
#define OrgMockitoAdditionalAnswers_

@protocol JavaUtilCollection;
@protocol OrgMockitoStubbingAnswer;

@interface OrgMockitoAdditionalAnswers : NSObject

#pragma mark Public

- (instancetype)init;

+ (id<OrgMockitoStubbingAnswer>)delegatesToWithId:(id)delegate;

+ (id<OrgMockitoStubbingAnswer>)returnsArgAtWithInt:(jint)position;

+ (id<OrgMockitoStubbingAnswer>)returnsElementsOfWithJavaUtilCollection:(id<JavaUtilCollection>)elements;

+ (id<OrgMockitoStubbingAnswer>)returnsFirstArg;

+ (id<OrgMockitoStubbingAnswer>)returnsLastArg;

+ (id<OrgMockitoStubbingAnswer>)returnsSecondArg;

@end

J2OBJC_STATIC_INIT(OrgMockitoAdditionalAnswers)

FOUNDATION_EXPORT void OrgMockitoAdditionalAnswers_init(OrgMockitoAdditionalAnswers *self);

FOUNDATION_EXPORT OrgMockitoAdditionalAnswers *new_OrgMockitoAdditionalAnswers_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoAdditionalAnswers *create_OrgMockitoAdditionalAnswers_init();

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoAdditionalAnswers_returnsFirstArg();

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoAdditionalAnswers_returnsSecondArg();

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoAdditionalAnswers_returnsLastArg();

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoAdditionalAnswers_returnsArgAtWithInt_(jint position);

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoAdditionalAnswers_delegatesToWithId_(id delegate);

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoAdditionalAnswers_returnsElementsOfWithJavaUtilCollection_(id<JavaUtilCollection> elements);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoAdditionalAnswers)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoAdditionalAnswers")
