//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/Captor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoCaptor")
#ifdef RESTRICT_OrgMockitoCaptor
#define INCLUDE_ALL_OrgMockitoCaptor 0
#else
#define INCLUDE_ALL_OrgMockitoCaptor 1
#endif
#undef RESTRICT_OrgMockitoCaptor

#if !defined (OrgMockitoCaptor_) && (INCLUDE_ALL_OrgMockitoCaptor || defined(INCLUDE_OrgMockitoCaptor))
#define OrgMockitoCaptor_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol OrgMockitoCaptor < JavaLangAnnotationAnnotation >

@end

@interface OrgMockitoCaptor : NSObject < OrgMockitoCaptor >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoCaptor)

FOUNDATION_EXPORT id<OrgMockitoCaptor> create_OrgMockitoCaptor();

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoCaptor)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoCaptor")
