//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/scalebar/DistanceUnitAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapScalebarDistanceUnitAdapter")
#ifdef RESTRICT_OrgMapsforgeMapScalebarDistanceUnitAdapter
#define INCLUDE_ALL_OrgMapsforgeMapScalebarDistanceUnitAdapter 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapScalebarDistanceUnitAdapter 1
#endif
#undef RESTRICT_OrgMapsforgeMapScalebarDistanceUnitAdapter

#if !defined (OrgMapsforgeMapScalebarDistanceUnitAdapter_) && (INCLUDE_ALL_OrgMapsforgeMapScalebarDistanceUnitAdapter || defined(INCLUDE_OrgMapsforgeMapScalebarDistanceUnitAdapter))
#define OrgMapsforgeMapScalebarDistanceUnitAdapter_

@class IOSIntArray;

@protocol OrgMapsforgeMapScalebarDistanceUnitAdapter < JavaObject >

- (jdouble)getMeterRatio;

- (IOSIntArray *)getScaleBarValues;

- (NSString *)getScaleTextWithInt:(jint)mapScaleValue;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapScalebarDistanceUnitAdapter)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapScalebarDistanceUnitAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapScalebarDistanceUnitAdapter")
