//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/scalebar/ImperialUnitAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapScalebarImperialUnitAdapter")
#ifdef RESTRICT_OrgMapsforgeMapScalebarImperialUnitAdapter
#define INCLUDE_ALL_OrgMapsforgeMapScalebarImperialUnitAdapter 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapScalebarImperialUnitAdapter 1
#endif
#undef RESTRICT_OrgMapsforgeMapScalebarImperialUnitAdapter

#if !defined (OrgMapsforgeMapScalebarImperialUnitAdapter_) && (INCLUDE_ALL_OrgMapsforgeMapScalebarImperialUnitAdapter || defined(INCLUDE_OrgMapsforgeMapScalebarImperialUnitAdapter))
#define OrgMapsforgeMapScalebarImperialUnitAdapter_

#define RESTRICT_OrgMapsforgeMapScalebarDistanceUnitAdapter 1
#define INCLUDE_OrgMapsforgeMapScalebarDistanceUnitAdapter 1
#include "org/mapsforge/map/scalebar/DistanceUnitAdapter.h"

@class IOSIntArray;

@interface OrgMapsforgeMapScalebarImperialUnitAdapter : NSObject < OrgMapsforgeMapScalebarDistanceUnitAdapter >

#pragma mark Public

- (jdouble)getMeterRatio;

- (IOSIntArray *)getScaleBarValues;

- (NSString *)getScaleTextWithInt:(jint)mapScaleValue;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapScalebarImperialUnitAdapter)

inline OrgMapsforgeMapScalebarImperialUnitAdapter *OrgMapsforgeMapScalebarImperialUnitAdapter_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMapsforgeMapScalebarImperialUnitAdapter *OrgMapsforgeMapScalebarImperialUnitAdapter_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMapsforgeMapScalebarImperialUnitAdapter, INSTANCE, OrgMapsforgeMapScalebarImperialUnitAdapter *)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapScalebarImperialUnitAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapScalebarImperialUnitAdapter")
