//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/scalebar/MapScaleBar.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapScalebarMapScaleBar")
#ifdef RESTRICT_OrgMapsforgeMapScalebarMapScaleBar
#define INCLUDE_ALL_OrgMapsforgeMapScalebarMapScaleBar 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapScalebarMapScaleBar 1
#endif
#undef RESTRICT_OrgMapsforgeMapScalebarMapScaleBar

#if !defined (OrgMapsforgeMapScalebarMapScaleBar_) && (INCLUDE_ALL_OrgMapsforgeMapScalebarMapScaleBar || defined(INCLUDE_OrgMapsforgeMapScalebarMapScaleBar))
#define OrgMapsforgeMapScalebarMapScaleBar_

@class OrgMapsforgeMapModelDisplayModel;
@class OrgMapsforgeMapModelMapViewDimension;
@class OrgMapsforgeMapModelMapViewPosition;
@class OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue;
@protocol OrgMapsforgeCoreGraphicsCanvas;
@protocol OrgMapsforgeCoreGraphicsGraphicContext;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgMapsforgeMapScalebarDistanceUnitAdapter;

@interface OrgMapsforgeMapScalebarMapScaleBar : NSObject {
 @public
  OrgMapsforgeMapModelDisplayModel *displayModel_;
  id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory_;
  id<OrgMapsforgeCoreGraphicsCanvas> mapScaleCanvas_;
  id<OrgMapsforgeMapScalebarDistanceUnitAdapter> distanceUnitAdapter_;
  jboolean visible_;
  jboolean redrawNeeded_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapModelMapViewPosition:(OrgMapsforgeMapModelMapViewPosition *)mapViewPosition
                   withOrgMapsforgeMapModelMapViewDimension:(OrgMapsforgeMapModelMapViewDimension *)mapViewDimension
                       withOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel
                 withOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory
                                                    withInt:(jint)width
                                                    withInt:(jint)height;

- (void)destroy;

- (void)drawWithOrgMapsforgeCoreGraphicsGraphicContext:(id<OrgMapsforgeCoreGraphicsGraphicContext>)graphicContext;

- (id<OrgMapsforgeMapScalebarDistanceUnitAdapter>)getDistanceUnitAdapter;

- (jboolean)isVisible;

- (void)redrawScaleBar;

- (void)setDistanceUnitAdapterWithOrgMapsforgeMapScalebarDistanceUnitAdapter:(id<OrgMapsforgeMapScalebarDistanceUnitAdapter>)distanceUnitAdapter;

- (void)setVisibleWithBoolean:(jboolean)visible;

#pragma mark Protected

- (OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue *)calculateScaleBarLengthAndValue;

- (OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue *)calculateScaleBarLengthAndValueWithOrgMapsforgeMapScalebarDistanceUnitAdapter:(id<OrgMapsforgeMapScalebarDistanceUnitAdapter>)unitAdapter;

- (void)redrawWithOrgMapsforgeCoreGraphicsCanvas:(id<OrgMapsforgeCoreGraphicsCanvas>)canvas;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapScalebarMapScaleBar)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapScalebarMapScaleBar, displayModel_, OrgMapsforgeMapModelDisplayModel *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapScalebarMapScaleBar, graphicFactory_, id<OrgMapsforgeCoreGraphicsGraphicFactory>)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapScalebarMapScaleBar, mapScaleCanvas_, id<OrgMapsforgeCoreGraphicsCanvas>)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapScalebarMapScaleBar, distanceUnitAdapter_, id<OrgMapsforgeMapScalebarDistanceUnitAdapter>)

FOUNDATION_EXPORT void OrgMapsforgeMapScalebarMapScaleBar_initWithOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeMapModelMapViewDimension_withOrgMapsforgeMapModelDisplayModel_withOrgMapsforgeCoreGraphicsGraphicFactory_withInt_withInt_(OrgMapsforgeMapScalebarMapScaleBar *self, OrgMapsforgeMapModelMapViewPosition *mapViewPosition, OrgMapsforgeMapModelMapViewDimension *mapViewDimension, OrgMapsforgeMapModelDisplayModel *displayModel, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, jint width, jint height);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapScalebarMapScaleBar)

#endif

#if !defined (OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue_) && (INCLUDE_ALL_OrgMapsforgeMapScalebarMapScaleBar || defined(INCLUDE_OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue))
#define OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue_

@interface OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue : NSObject {
 @public
  jint scaleBarLength_;
  jint scaleBarValue_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)scaleBarLength
                    withInt:(jint)scaleBarValue;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue)

FOUNDATION_EXPORT void OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue_initWithInt_withInt_(OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue *self, jint scaleBarLength, jint scaleBarValue);

FOUNDATION_EXPORT OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue *new_OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue_initWithInt_withInt_(jint scaleBarLength, jint scaleBarValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue *create_OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue_initWithInt_withInt_(jint scaleBarLength, jint scaleBarValue);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapScalebarMapScaleBar_ScaleBarLengthAndValue)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapScalebarMapScaleBar")
