//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/stubbing/DeprecatedOngoingStubbing.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoStubbingDeprecatedOngoingStubbing")
#ifdef RESTRICT_OrgMockitoStubbingDeprecatedOngoingStubbing
#define INCLUDE_ALL_OrgMockitoStubbingDeprecatedOngoingStubbing 0
#else
#define INCLUDE_ALL_OrgMockitoStubbingDeprecatedOngoingStubbing 1
#endif
#undef RESTRICT_OrgMockitoStubbingDeprecatedOngoingStubbing

#if !defined (OrgMockitoStubbingDeprecatedOngoingStubbing_) && (INCLUDE_ALL_OrgMockitoStubbingDeprecatedOngoingStubbing || defined(INCLUDE_OrgMockitoStubbingDeprecatedOngoingStubbing))
#define OrgMockitoStubbingDeprecatedOngoingStubbing_

#define RESTRICT_OrgMockitoInternalProgressIOngoingStubbing 1
#define INCLUDE_OrgMockitoInternalProgressIOngoingStubbing 1
#include "org/mockito/internal/progress/IOngoingStubbing.h"

@protocol OrgMockitoStubbingAnswer;

@protocol OrgMockitoStubbingDeprecatedOngoingStubbing < OrgMockitoInternalProgressIOngoingStubbing, JavaObject >

- (id<OrgMockitoStubbingDeprecatedOngoingStubbing>)toReturnWithId:(id)value;

- (id<OrgMockitoStubbingDeprecatedOngoingStubbing>)toThrowWithNSException:(NSException *)throwable;
#define toThrowWithJavaLangThrowable toThrowWithNSException

- (id<OrgMockitoStubbingDeprecatedOngoingStubbing>)toAnswerWithOrgMockitoStubbingAnswer:(id<OrgMockitoStubbingAnswer>)answer;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoStubbingDeprecatedOngoingStubbing)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoStubbingDeprecatedOngoingStubbing)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoStubbingDeprecatedOngoingStubbing")
