//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/stubbing/VoidMethodStubbable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoStubbingVoidMethodStubbable")
#ifdef RESTRICT_OrgMockitoStubbingVoidMethodStubbable
#define INCLUDE_ALL_OrgMockitoStubbingVoidMethodStubbable 0
#else
#define INCLUDE_ALL_OrgMockitoStubbingVoidMethodStubbable 1
#endif
#undef RESTRICT_OrgMockitoStubbingVoidMethodStubbable

#if !defined (OrgMockitoStubbingVoidMethodStubbable_) && (INCLUDE_ALL_OrgMockitoStubbingVoidMethodStubbable || defined(INCLUDE_OrgMockitoStubbingVoidMethodStubbable))
#define OrgMockitoStubbingVoidMethodStubbable_

@protocol OrgMockitoStubbingAnswer;

@protocol OrgMockitoStubbingVoidMethodStubbable < JavaObject >

- (id<OrgMockitoStubbingVoidMethodStubbable>)toThrowWithNSException:(NSException *)throwable;
#define toThrowWithJavaLangThrowable toThrowWithNSException

- (id<OrgMockitoStubbingVoidMethodStubbable>)toReturn;

- (id<OrgMockitoStubbingVoidMethodStubbable>)toAnswerWithOrgMockitoStubbingAnswer:(id<OrgMockitoStubbingAnswer>)answer;

- (id)on;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoStubbingVoidMethodStubbable)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoStubbingVoidMethodStubbable)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoStubbingVoidMethodStubbable")
