//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/junit/runner/notification/RunListener.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnerNotificationRunListener")
#ifdef RESTRICT_OrgJunitRunnerNotificationRunListener
#define INCLUDE_ALL_OrgJunitRunnerNotificationRunListener 0
#else
#define INCLUDE_ALL_OrgJunitRunnerNotificationRunListener 1
#endif
#undef RESTRICT_OrgJunitRunnerNotificationRunListener

#if !defined (OrgJunitRunnerNotificationRunListener_) && (INCLUDE_ALL_OrgJunitRunnerNotificationRunListener || defined(INCLUDE_OrgJunitRunnerNotificationRunListener))
#define OrgJunitRunnerNotificationRunListener_

@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationFailure;
@class OrgJunitRunnerResult;

@interface OrgJunitRunnerNotificationRunListener : NSObject

#pragma mark Public

- (instancetype)init;

- (void)testAssumptionFailureWithOrgJunitRunnerNotificationFailure:(OrgJunitRunnerNotificationFailure *)failure;

- (void)testFailureWithOrgJunitRunnerNotificationFailure:(OrgJunitRunnerNotificationFailure *)failure;

- (void)testFinishedWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (void)testIgnoredWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (void)testRunFinishedWithOrgJunitRunnerResult:(OrgJunitRunnerResult *)result;

- (void)testRunStartedWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (void)testStartedWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnerNotificationRunListener)

FOUNDATION_EXPORT void OrgJunitRunnerNotificationRunListener_init(OrgJunitRunnerNotificationRunListener *self);

FOUNDATION_EXPORT OrgJunitRunnerNotificationRunListener *new_OrgJunitRunnerNotificationRunListener_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitRunnerNotificationRunListener *create_OrgJunitRunnerNotificationRunListener_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnerNotificationRunListener)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnerNotificationRunListener")
