//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/Layer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerLayer")
#ifdef RESTRICT_OrgMapsforgeMapLayerLayer
#define INCLUDE_ALL_OrgMapsforgeMapLayerLayer 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerLayer 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerLayer

#if !defined (OrgMapsforgeMapLayerLayer_) && (INCLUDE_ALL_OrgMapsforgeMapLayerLayer || defined(INCLUDE_OrgMapsforgeMapLayerLayer))
#define OrgMapsforgeMapLayerLayer_

@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelLatLong;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeMapModelDisplayModel;
@protocol OrgMapsforgeCoreGraphicsCanvas;
@protocol OrgMapsforgeMapLayerRedrawer;

@interface OrgMapsforgeMapLayerLayer : NSObject {
 @public
  OrgMapsforgeMapModelDisplayModel *displayModel_;
}

#pragma mark Public

- (instancetype)init;

- (void)drawWithOrgMapsforgeCoreModelBoundingBox:(OrgMapsforgeCoreModelBoundingBox *)boundingBox
                                        withByte:(jbyte)zoomLevel
              withOrgMapsforgeCoreGraphicsCanvas:(id<OrgMapsforgeCoreGraphicsCanvas>)canvas
                  withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)topLeftPoint;

- (OrgMapsforgeCoreModelLatLong *)getPosition;

- (jboolean)isVisible;

- (void)onDestroy;

- (jboolean)onLongPressWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)tapLatLong
                         withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)layerXY
                         withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)tapXY;

- (jboolean)onTapWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)tapLatLong
                   withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)layerXY
                   withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)tapXY;

- (void)requestRedraw;

- (void)setDisplayModelWithOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel;

- (void)setVisibleWithBoolean:(jboolean)visible;

#pragma mark Protected

- (void)onAdd;

- (void)onRemove;

#pragma mark Package-Private

- (void)assignWithOrgMapsforgeMapLayerRedrawer:(id<OrgMapsforgeMapLayerRedrawer>)redrawer;

- (void)unassign;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerLayer)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerLayer, displayModel_, OrgMapsforgeMapModelDisplayModel *)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerLayer_init(OrgMapsforgeMapLayerLayer *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerLayer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerLayer")
