//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/LayerManager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerLayerManager")
#ifdef RESTRICT_OrgMapsforgeMapLayerLayerManager
#define INCLUDE_ALL_OrgMapsforgeMapLayerLayerManager 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerLayerManager 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerLayerManager

#if !defined (OrgMapsforgeMapLayerLayerManager_) && (INCLUDE_ALL_OrgMapsforgeMapLayerLayerManager || defined(INCLUDE_OrgMapsforgeMapLayerLayerManager))
#define OrgMapsforgeMapLayerLayerManager_

#define RESTRICT_OrgMapsforgeMapUtilPausableThread 1
#define INCLUDE_OrgMapsforgeMapUtilPausableThread 1
#include "org/mapsforge/map/util/PausableThread.h"

#define RESTRICT_OrgMapsforgeMapLayerRedrawer 1
#define INCLUDE_OrgMapsforgeMapLayerRedrawer 1
#include "org/mapsforge/map/layer/Redrawer.h"

@class OrgMapsforgeMapLayerLayers;
@class OrgMapsforgeMapModelMapViewPosition;
@class OrgMapsforgeMapUtilPausableThread_ThreadPriority;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgMapsforgeMapViewMapView;

@interface OrgMapsforgeMapLayerLayerManager : OrgMapsforgeMapUtilPausableThread < OrgMapsforgeMapLayerRedrawer >

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapViewMapView:(id<OrgMapsforgeMapViewMapView>)mapView
           withOrgMapsforgeMapModelMapViewPosition:(OrgMapsforgeMapModelMapViewPosition *)mapViewPosition
        withOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory;

- (OrgMapsforgeMapLayerLayers *)getLayers;

- (void)redrawLayers;

#pragma mark Protected

- (void)afterRun;

- (void)doWork;

- (OrgMapsforgeMapUtilPausableThread_ThreadPriority *)getThreadPriority;

- (jboolean)hasWork;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerLayerManager)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerLayerManager_initWithOrgMapsforgeMapViewMapView_withOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeCoreGraphicsGraphicFactory_(OrgMapsforgeMapLayerLayerManager *self, id<OrgMapsforgeMapViewMapView> mapView, OrgMapsforgeMapModelMapViewPosition *mapViewPosition, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory);

FOUNDATION_EXPORT OrgMapsforgeMapLayerLayerManager *new_OrgMapsforgeMapLayerLayerManager_initWithOrgMapsforgeMapViewMapView_withOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeCoreGraphicsGraphicFactory_(id<OrgMapsforgeMapViewMapView> mapView, OrgMapsforgeMapModelMapViewPosition *mapViewPosition, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapLayerLayerManager *create_OrgMapsforgeMapLayerLayerManager_initWithOrgMapsforgeMapViewMapView_withOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeCoreGraphicsGraphicFactory_(id<OrgMapsforgeMapViewMapView> mapView, OrgMapsforgeMapModelMapViewPosition *mapViewPosition, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerLayerManager)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerLayerManager")
