//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/Redrawer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRedrawer")
#ifdef RESTRICT_OrgMapsforgeMapLayerRedrawer
#define INCLUDE_ALL_OrgMapsforgeMapLayerRedrawer 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerRedrawer 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerRedrawer

#if !defined (OrgMapsforgeMapLayerRedrawer_) && (INCLUDE_ALL_OrgMapsforgeMapLayerRedrawer || defined(INCLUDE_OrgMapsforgeMapLayerRedrawer))
#define OrgMapsforgeMapLayerRedrawer_

@protocol OrgMapsforgeMapLayerRedrawer < JavaObject >

- (void)redrawLayers;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerRedrawer)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerRedrawer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRedrawer")
