//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/TilePosition.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerTilePosition")
#ifdef RESTRICT_OrgMapsforgeMapLayerTilePosition
#define INCLUDE_ALL_OrgMapsforgeMapLayerTilePosition 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerTilePosition 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerTilePosition

#if !defined (OrgMapsforgeMapLayerTilePosition_) && (INCLUDE_ALL_OrgMapsforgeMapLayerTilePosition || defined(INCLUDE_OrgMapsforgeMapLayerTilePosition))
#define OrgMapsforgeMapLayerTilePosition_

@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelTile;

@interface OrgMapsforgeMapLayerTilePosition : NSObject {
 @public
  OrgMapsforgeCoreModelPoint *point_;
  OrgMapsforgeCoreModelTile *tile_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile
                   withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)point;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerTilePosition)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerTilePosition, point_, OrgMapsforgeCoreModelPoint *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerTilePosition, tile_, OrgMapsforgeCoreModelTile *)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerTilePosition_initWithOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeMapLayerTilePosition *self, OrgMapsforgeCoreModelTile *tile, OrgMapsforgeCoreModelPoint *point);

FOUNDATION_EXPORT OrgMapsforgeMapLayerTilePosition *new_OrgMapsforgeMapLayerTilePosition_initWithOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelTile *tile, OrgMapsforgeCoreModelPoint *point) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapLayerTilePosition *create_OrgMapsforgeMapLayerTilePosition_initWithOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelTile *tile, OrgMapsforgeCoreModelPoint *point);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerTilePosition)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerTilePosition")
