//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/matchers/ContainsExtraTypeInformation.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalMatchersContainsExtraTypeInformation")
#ifdef RESTRICT_OrgMockitoInternalMatchersContainsExtraTypeInformation
#define INCLUDE_ALL_OrgMockitoInternalMatchersContainsExtraTypeInformation 0
#else
#define INCLUDE_ALL_OrgMockitoInternalMatchersContainsExtraTypeInformation 1
#endif
#undef RESTRICT_OrgMockitoInternalMatchersContainsExtraTypeInformation

#if !defined (OrgMockitoInternalMatchersContainsExtraTypeInformation_) && (INCLUDE_ALL_OrgMockitoInternalMatchersContainsExtraTypeInformation || defined(INCLUDE_OrgMockitoInternalMatchersContainsExtraTypeInformation))
#define OrgMockitoInternalMatchersContainsExtraTypeInformation_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@protocol OrgHamcrestSelfDescribing;

@protocol OrgMockitoInternalMatchersContainsExtraTypeInformation < JavaIoSerializable, JavaObject >

- (id<OrgHamcrestSelfDescribing>)withExtraTypeInfo;

- (jboolean)typeMatchesWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalMatchersContainsExtraTypeInformation)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalMatchersContainsExtraTypeInformation)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalMatchersContainsExtraTypeInformation")
