//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/stubbing/InvocationContainer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalStubbingInvocationContainer")
#ifdef RESTRICT_OrgMockitoInternalStubbingInvocationContainer
#define INCLUDE_ALL_OrgMockitoInternalStubbingInvocationContainer 0
#else
#define INCLUDE_ALL_OrgMockitoInternalStubbingInvocationContainer 1
#endif
#undef RESTRICT_OrgMockitoInternalStubbingInvocationContainer

#if !defined (OrgMockitoInternalStubbingInvocationContainer_) && (INCLUDE_ALL_OrgMockitoInternalStubbingInvocationContainer || defined(INCLUDE_OrgMockitoInternalStubbingInvocationContainer))
#define OrgMockitoInternalStubbingInvocationContainer_

@protocol JavaUtilList;

@protocol OrgMockitoInternalStubbingInvocationContainer < JavaObject >

- (id<JavaUtilList>)getInvocations;

- (id<JavaUtilList>)getStubbedInvocations;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalStubbingInvocationContainer)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalStubbingInvocationContainer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalStubbingInvocationContainer")
