//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/util/LatLongUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilLatLongUtils")
#ifdef RESTRICT_OrgMapsforgeCoreUtilLatLongUtils
#define INCLUDE_ALL_OrgMapsforgeCoreUtilLatLongUtils 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreUtilLatLongUtils 1
#endif
#undef RESTRICT_OrgMapsforgeCoreUtilLatLongUtils

#if !defined (OrgMapsforgeCoreUtilLatLongUtils_) && (INCLUDE_ALL_OrgMapsforgeCoreUtilLatLongUtils || defined(INCLUDE_OrgMapsforgeCoreUtilLatLongUtils))
#define OrgMapsforgeCoreUtilLatLongUtils_

@class IOSDoubleArray;
@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelDimension;
@class OrgMapsforgeCoreModelLatLong;

@interface OrgMapsforgeCoreUtilLatLongUtils : NSObject

#pragma mark Public

+ (jint)degreesToMicrodegreesWithDouble:(jdouble)coordinate;

+ (OrgMapsforgeCoreModelLatLong *)fromStringWithNSString:(NSString *)latLongString;

+ (jdouble)latitudeDistanceWithInt:(jint)meters;

+ (jdouble)longitudeDistanceWithInt:(jint)meters
                         withDouble:(jdouble)latitude;

+ (jdouble)microdegreesToDegreesWithInt:(jint)coordinate;

+ (IOSDoubleArray *)parseCoordinateStringWithNSString:(NSString *)coordinatesString
                                              withInt:(jint)numberOfCoordinates;

+ (void)validateLatitudeWithDouble:(jdouble)latitude;

+ (void)validateLongitudeWithDouble:(jdouble)longitude;

+ (jbyte)zoomForBoundsWithOrgMapsforgeCoreModelDimension:(OrgMapsforgeCoreModelDimension *)dimension
                    withOrgMapsforgeCoreModelBoundingBox:(OrgMapsforgeCoreModelBoundingBox *)boundingBox
                                                 withInt:(jint)tileSize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreUtilLatLongUtils)

inline jdouble OrgMapsforgeCoreUtilLatLongUtils_get_EQUATORIAL_RADIUS();
#define OrgMapsforgeCoreUtilLatLongUtils_EQUATORIAL_RADIUS 6378137.0
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreUtilLatLongUtils, EQUATORIAL_RADIUS, jdouble)

inline jdouble OrgMapsforgeCoreUtilLatLongUtils_get_LATITUDE_MAX();
#define OrgMapsforgeCoreUtilLatLongUtils_LATITUDE_MAX 90.0
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreUtilLatLongUtils, LATITUDE_MAX, jdouble)

inline jdouble OrgMapsforgeCoreUtilLatLongUtils_get_LATITUDE_MIN();
#define OrgMapsforgeCoreUtilLatLongUtils_LATITUDE_MIN -90.0
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreUtilLatLongUtils, LATITUDE_MIN, jdouble)

inline jdouble OrgMapsforgeCoreUtilLatLongUtils_get_LONGITUDE_MAX();
#define OrgMapsforgeCoreUtilLatLongUtils_LONGITUDE_MAX 180.0
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreUtilLatLongUtils, LONGITUDE_MAX, jdouble)

inline jdouble OrgMapsforgeCoreUtilLatLongUtils_get_LONGITUDE_MIN();
#define OrgMapsforgeCoreUtilLatLongUtils_LONGITUDE_MIN -180.0
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreUtilLatLongUtils, LONGITUDE_MIN, jdouble)

FOUNDATION_EXPORT jint OrgMapsforgeCoreUtilLatLongUtils_degreesToMicrodegreesWithDouble_(jdouble coordinate);

FOUNDATION_EXPORT OrgMapsforgeCoreModelLatLong *OrgMapsforgeCoreUtilLatLongUtils_fromStringWithNSString_(NSString *latLongString);

FOUNDATION_EXPORT jdouble OrgMapsforgeCoreUtilLatLongUtils_latitudeDistanceWithInt_(jint meters);

FOUNDATION_EXPORT jdouble OrgMapsforgeCoreUtilLatLongUtils_longitudeDistanceWithInt_withDouble_(jint meters, jdouble latitude);

FOUNDATION_EXPORT jdouble OrgMapsforgeCoreUtilLatLongUtils_microdegreesToDegreesWithInt_(jint coordinate);

FOUNDATION_EXPORT IOSDoubleArray *OrgMapsforgeCoreUtilLatLongUtils_parseCoordinateStringWithNSString_withInt_(NSString *coordinatesString, jint numberOfCoordinates);

FOUNDATION_EXPORT void OrgMapsforgeCoreUtilLatLongUtils_validateLatitudeWithDouble_(jdouble latitude);

FOUNDATION_EXPORT void OrgMapsforgeCoreUtilLatLongUtils_validateLongitudeWithDouble_(jdouble longitude);

FOUNDATION_EXPORT jbyte OrgMapsforgeCoreUtilLatLongUtils_zoomForBoundsWithOrgMapsforgeCoreModelDimension_withOrgMapsforgeCoreModelBoundingBox_withInt_(OrgMapsforgeCoreModelDimension *dimension, OrgMapsforgeCoreModelBoundingBox *boundingBox, jint tileSize);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreUtilLatLongUtils)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilLatLongUtils")
