//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/runners/RunnerImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalRunnersRunnerImpl")
#ifdef RESTRICT_OrgMockitoInternalRunnersRunnerImpl
#define INCLUDE_ALL_OrgMockitoInternalRunnersRunnerImpl 0
#else
#define INCLUDE_ALL_OrgMockitoInternalRunnersRunnerImpl 1
#endif
#undef RESTRICT_OrgMockitoInternalRunnersRunnerImpl

#if !defined (OrgMockitoInternalRunnersRunnerImpl_) && (INCLUDE_ALL_OrgMockitoInternalRunnersRunnerImpl || defined(INCLUDE_OrgMockitoInternalRunnersRunnerImpl))
#define OrgMockitoInternalRunnersRunnerImpl_

#define RESTRICT_OrgJunitRunnerManipulationFilterable 1
#define INCLUDE_OrgJunitRunnerManipulationFilterable 1
#include "org/junit/runner/manipulation/Filterable.h"

@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationRunNotifier;

@protocol OrgMockitoInternalRunnersRunnerImpl < OrgJunitRunnerManipulationFilterable, JavaObject >

- (void)runWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;

- (OrgJunitRunnerDescription *)getDescription;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalRunnersRunnerImpl)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalRunnersRunnerImpl)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalRunnersRunnerImpl")
