//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/renderinstruction/Caption.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionCaption")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionCaption
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionCaption 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionCaption 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionCaption

#if !defined (OrgMapsforgeMapRenderthemeRenderinstructionCaption_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionCaption || defined(INCLUDE_OrgMapsforgeMapRenderthemeRenderinstructionCaption))
#define OrgMapsforgeMapRenderthemeRenderinstructionCaption_

#define RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction 1
#define INCLUDE_OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction 1
#include "org/mapsforge/map/rendertheme/renderinstruction/RenderInstruction.h"

@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapLayerRendererPolylineContainer;
@class OrgMapsforgeMapModelDisplayModel;
@class OrgMapsforgeMapReaderPointOfInterest;
@protocol JavaUtilMap;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgMapsforgeMapRenderthemeRenderCallback;
@protocol OrgXmlpullV1XmlPullParser;

@interface OrgMapsforgeMapRenderthemeRenderinstructionCaption : OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction {
 @public
  NSString *symbolId_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory
                          withOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel
                                                  withNSString:(NSString *)elementName
                                 withOrgXmlpullV1XmlPullParser:(id<OrgXmlpullV1XmlPullParser>)pullParser
                                               withJavaUtilMap:(id<JavaUtilMap>)symbols;

- (void)destroy;

- (void)renderNodeWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
                      withOrgMapsforgeMapReaderPointOfInterest:(OrgMapsforgeMapReaderPointOfInterest *)poi
                                 withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)renderWayWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
            withOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way;

- (void)scaleStrokeWidthWithFloat:(jfloat)scaleFactor;

- (void)scaleTextSizeWithFloat:(jfloat)scaleFactor;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRenderinstructionCaption)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapRenderthemeRenderinstructionCaption, symbolId_, NSString *)

inline jfloat OrgMapsforgeMapRenderthemeRenderinstructionCaption_get_DEFAULT_GAP();
#define OrgMapsforgeMapRenderthemeRenderinstructionCaption_DEFAULT_GAP 5.0f
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeMapRenderthemeRenderinstructionCaption, DEFAULT_GAP, jfloat)

FOUNDATION_EXPORT void OrgMapsforgeMapRenderthemeRenderinstructionCaption_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_withJavaUtilMap_(OrgMapsforgeMapRenderthemeRenderinstructionCaption *self, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser, id<JavaUtilMap> symbols);

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRenderinstructionCaption *new_OrgMapsforgeMapRenderthemeRenderinstructionCaption_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_withJavaUtilMap_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser, id<JavaUtilMap> symbols) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRenderinstructionCaption *create_OrgMapsforgeMapRenderthemeRenderinstructionCaption_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_withJavaUtilMap_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser, id<JavaUtilMap> symbols);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRenderinstructionCaption)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionCaption")
