//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/renderinstruction/LineSymbol.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol

#if !defined (OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol || defined(INCLUDE_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol))
#define OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol_

#define RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction 1
#define INCLUDE_OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction 1
#include "org/mapsforge/map/rendertheme/renderinstruction/RenderInstruction.h"

@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapLayerRendererPolylineContainer;
@class OrgMapsforgeMapModelDisplayModel;
@class OrgMapsforgeMapReaderPointOfInterest;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgMapsforgeMapRenderthemeRenderCallback;
@protocol OrgXmlpullV1XmlPullParser;

@interface OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol : OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory
                          withOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel
                                                  withNSString:(NSString *)elementName
                                 withOrgXmlpullV1XmlPullParser:(id<OrgXmlpullV1XmlPullParser>)pullParser
                                                  withNSString:(NSString *)relativePathPrefix;

- (void)destroy;

- (void)renderNodeWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
                      withOrgMapsforgeMapReaderPointOfInterest:(OrgMapsforgeMapReaderPointOfInterest *)poi
                                 withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)renderWayWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
            withOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way;

- (void)scaleStrokeWidthWithFloat:(jfloat)scaleFactor;

- (void)scaleTextSizeWithFloat:(jfloat)scaleFactor;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol)

FOUNDATION_EXPORT void OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_withNSString_(OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol *self, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser, NSString *relativePathPrefix);

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol *new_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_withNSString_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser, NSString *relativePathPrefix) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol *create_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_withNSString_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser, NSString *relativePathPrefix);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionLineSymbol")
