//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/renderinstruction/PathText.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionPathText")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionPathText
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionPathText 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionPathText 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionPathText

#if !defined (OrgMapsforgeMapRenderthemeRenderinstructionPathText_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionPathText || defined(INCLUDE_OrgMapsforgeMapRenderthemeRenderinstructionPathText))
#define OrgMapsforgeMapRenderthemeRenderinstructionPathText_

#define RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction 1
#define INCLUDE_OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction 1
#include "org/mapsforge/map/rendertheme/renderinstruction/RenderInstruction.h"

@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapLayerRendererPolylineContainer;
@class OrgMapsforgeMapModelDisplayModel;
@class OrgMapsforgeMapReaderPointOfInterest;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgMapsforgeMapRenderthemeRenderCallback;
@protocol OrgXmlpullV1XmlPullParser;

@interface OrgMapsforgeMapRenderthemeRenderinstructionPathText : OrgMapsforgeMapRenderthemeRenderinstructionRenderInstruction

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory
                          withOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel
                                                  withNSString:(NSString *)elementName
                                 withOrgXmlpullV1XmlPullParser:(id<OrgXmlpullV1XmlPullParser>)pullParser;

- (void)destroy;

- (void)renderNodeWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
                      withOrgMapsforgeMapReaderPointOfInterest:(OrgMapsforgeMapReaderPointOfInterest *)poi
                                 withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)renderWayWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
            withOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way;

- (void)scaleStrokeWidthWithFloat:(jfloat)scaleFactor;

- (void)scaleTextSizeWithFloat:(jfloat)scaleFactor;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRenderinstructionPathText)

FOUNDATION_EXPORT void OrgMapsforgeMapRenderthemeRenderinstructionPathText_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_(OrgMapsforgeMapRenderthemeRenderinstructionPathText *self, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser);

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRenderinstructionPathText *new_OrgMapsforgeMapRenderthemeRenderinstructionPathText_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRenderinstructionPathText *create_OrgMapsforgeMapRenderthemeRenderinstructionPathText_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeMapModelDisplayModel_withNSString_withOrgXmlpullV1XmlPullParser_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeMapModelDisplayModel *displayModel, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRenderinstructionPathText)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionPathText")
