//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/renderinstruction/TextKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionTextKey")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionTextKey
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionTextKey 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionTextKey 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRenderinstructionTextKey

#if !defined (OrgMapsforgeMapRenderthemeRenderinstructionTextKey_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionTextKey || defined(INCLUDE_OrgMapsforgeMapRenderthemeRenderinstructionTextKey))
#define OrgMapsforgeMapRenderthemeRenderinstructionTextKey_

@protocol JavaUtilList;

@interface OrgMapsforgeMapRenderthemeRenderinstructionTextKey : NSObject

#pragma mark Package-Private

+ (OrgMapsforgeMapRenderthemeRenderinstructionTextKey *)getInstanceWithNSString:(NSString *)key;

- (NSString *)getValueWithJavaUtilList:(id<JavaUtilList>)tags;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapRenderthemeRenderinstructionTextKey)

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRenderinstructionTextKey *OrgMapsforgeMapRenderthemeRenderinstructionTextKey_getInstanceWithNSString_(NSString *key);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRenderinstructionTextKey)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderinstructionTextKey")
