//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/junit/framework/TestFailure.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JunitFrameworkTestFailure")
#ifdef RESTRICT_JunitFrameworkTestFailure
#define INCLUDE_ALL_JunitFrameworkTestFailure 0
#else
#define INCLUDE_ALL_JunitFrameworkTestFailure 1
#endif
#undef RESTRICT_JunitFrameworkTestFailure

#if !defined (JunitFrameworkTestFailure_) && (INCLUDE_ALL_JunitFrameworkTestFailure || defined(INCLUDE_JunitFrameworkTestFailure))
#define JunitFrameworkTestFailure_

@protocol JunitFrameworkTest;

@interface JunitFrameworkTestFailure : NSObject {
 @public
  id<JunitFrameworkTest> fFailedTest_;
  NSException *fThrownException_;
}

#pragma mark Public

- (instancetype)initWithJunitFrameworkTest:(id<JunitFrameworkTest>)failedTest
                           withNSException:(NSException *)thrownException;
#define withJavaLangThrowable withNSException

- (NSString *)exceptionMessage;

- (id<JunitFrameworkTest>)failedTest;

- (jboolean)isFailure;

- (NSException *)thrownException;

- (NSString *)description;

- (NSString *)trace;

@end

J2OBJC_EMPTY_STATIC_INIT(JunitFrameworkTestFailure)

J2OBJC_FIELD_SETTER(JunitFrameworkTestFailure, fFailedTest_, id<JunitFrameworkTest>)
J2OBJC_FIELD_SETTER(JunitFrameworkTestFailure, fThrownException_, NSException *)

FOUNDATION_EXPORT void JunitFrameworkTestFailure_initWithJunitFrameworkTest_withNSException_(JunitFrameworkTestFailure *self, id<JunitFrameworkTest> failedTest, NSException *thrownException);

FOUNDATION_EXPORT JunitFrameworkTestFailure *new_JunitFrameworkTestFailure_initWithJunitFrameworkTest_withNSException_(id<JunitFrameworkTest> failedTest, NSException *thrownException) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JunitFrameworkTestFailure *create_JunitFrameworkTestFailure_initWithJunitFrameworkTest_withNSException_(id<JunitFrameworkTest> failedTest, NSException *thrownException);

J2OBJC_TYPE_LITERAL_HEADER(JunitFrameworkTestFailure)

#endif

#pragma pop_macro("INCLUDE_ALL_JunitFrameworkTestFailure")
