//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/progress/SequenceNumber.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalProgressSequenceNumber")
#ifdef RESTRICT_OrgMockitoInternalProgressSequenceNumber
#define INCLUDE_ALL_OrgMockitoInternalProgressSequenceNumber 0
#else
#define INCLUDE_ALL_OrgMockitoInternalProgressSequenceNumber 1
#endif
#undef RESTRICT_OrgMockitoInternalProgressSequenceNumber

#if !defined (OrgMockitoInternalProgressSequenceNumber_) && (INCLUDE_ALL_OrgMockitoInternalProgressSequenceNumber || defined(INCLUDE_OrgMockitoInternalProgressSequenceNumber))
#define OrgMockitoInternalProgressSequenceNumber_

@interface OrgMockitoInternalProgressSequenceNumber : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)next;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalProgressSequenceNumber)

FOUNDATION_EXPORT void OrgMockitoInternalProgressSequenceNumber_init(OrgMockitoInternalProgressSequenceNumber *self);

FOUNDATION_EXPORT OrgMockitoInternalProgressSequenceNumber *new_OrgMockitoInternalProgressSequenceNumber_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalProgressSequenceNumber *create_OrgMockitoInternalProgressSequenceNumber_init();

FOUNDATION_EXPORT jint OrgMockitoInternalProgressSequenceNumber_next();

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalProgressSequenceNumber)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalProgressSequenceNumber")
