//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/invocation/MockitoMethod.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalInvocationMockitoMethod")
#ifdef RESTRICT_OrgMockitoInternalInvocationMockitoMethod
#define INCLUDE_ALL_OrgMockitoInternalInvocationMockitoMethod 0
#else
#define INCLUDE_ALL_OrgMockitoInternalInvocationMockitoMethod 1
#endif
#undef RESTRICT_OrgMockitoInternalInvocationMockitoMethod

#if !defined (OrgMockitoInternalInvocationMockitoMethod_) && (INCLUDE_ALL_OrgMockitoInternalInvocationMockitoMethod || defined(INCLUDE_OrgMockitoInternalInvocationMockitoMethod))
#define OrgMockitoInternalInvocationMockitoMethod_

@class IOSClass;
@class IOSObjectArray;
@class JavaLangReflectMethod;

@protocol OrgMockitoInternalInvocationMockitoMethod < JavaObject >

- (NSString *)getName;

- (IOSClass *)getReturnType;

- (IOSObjectArray *)getParameterTypes;

- (IOSObjectArray *)getExceptionTypes;

- (jboolean)isVarArgs;

- (JavaLangReflectMethod *)getJavaMethod;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalInvocationMockitoMethod)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalInvocationMockitoMethod)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalInvocationMockitoMethod")
