//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/security/PrivilegedActionException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaSecurityPrivilegedActionException")
#ifdef RESTRICT_JavaSecurityPrivilegedActionException
#define INCLUDE_ALL_JavaSecurityPrivilegedActionException 0
#else
#define INCLUDE_ALL_JavaSecurityPrivilegedActionException 1
#endif
#undef RESTRICT_JavaSecurityPrivilegedActionException

#if !defined (JavaSecurityPrivilegedActionException_) && (INCLUDE_ALL_JavaSecurityPrivilegedActionException || defined(INCLUDE_JavaSecurityPrivilegedActionException))
#define JavaSecurityPrivilegedActionException_

#define RESTRICT_JavaLangException 1
#define INCLUDE_JavaLangException 1
#include "java/lang/Exception.h"

/*!
 @brief Legacy security code; do not use.
 */
@interface JavaSecurityPrivilegedActionException : JavaLangException

#pragma mark Public

- (instancetype)initWithJavaLangException:(JavaLangException *)exception;

- (JavaLangException *)getException;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityPrivilegedActionException)

FOUNDATION_EXPORT void JavaSecurityPrivilegedActionException_initWithJavaLangException_(JavaSecurityPrivilegedActionException *self, JavaLangException *exception);

FOUNDATION_EXPORT JavaSecurityPrivilegedActionException *new_JavaSecurityPrivilegedActionException_initWithJavaLangException_(JavaLangException *exception) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaSecurityPrivilegedActionException *create_JavaSecurityPrivilegedActionException_initWithJavaLangException_(JavaLangException *exception);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityPrivilegedActionException)

#endif

#pragma pop_macro("INCLUDE_ALL_JavaSecurityPrivilegedActionException")
