//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/junit/runner/manipulation/Sorter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnerManipulationSorter")
#ifdef RESTRICT_OrgJunitRunnerManipulationSorter
#define INCLUDE_ALL_OrgJunitRunnerManipulationSorter 0
#else
#define INCLUDE_ALL_OrgJunitRunnerManipulationSorter 1
#endif
#undef RESTRICT_OrgJunitRunnerManipulationSorter

#if !defined (OrgJunitRunnerManipulationSorter_) && (INCLUDE_ALL_OrgJunitRunnerManipulationSorter || defined(INCLUDE_OrgJunitRunnerManipulationSorter))
#define OrgJunitRunnerManipulationSorter_

#define RESTRICT_JavaUtilComparator 1
#define INCLUDE_JavaUtilComparator 1
#include "java/util/Comparator.h"

@class OrgJunitRunnerDescription;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilFunctionToDoubleFunction;
@protocol JavaUtilFunctionToIntFunction;
@protocol JavaUtilFunctionToLongFunction;

@interface OrgJunitRunnerManipulationSorter : NSObject < JavaUtilComparator >

#pragma mark Public

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

- (void)applyWithId:(id)object;

- (jint)compareWithId:(OrgJunitRunnerDescription *)o1
               withId:(OrgJunitRunnerDescription *)o2;

@end

J2OBJC_STATIC_INIT(OrgJunitRunnerManipulationSorter)

inline OrgJunitRunnerManipulationSorter *OrgJunitRunnerManipulationSorter_get_NULL();
inline OrgJunitRunnerManipulationSorter *OrgJunitRunnerManipulationSorter_set_NULL(OrgJunitRunnerManipulationSorter *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJunitRunnerManipulationSorter *OrgJunitRunnerManipulationSorter_NULL;
J2OBJC_STATIC_FIELD_OBJ(OrgJunitRunnerManipulationSorter, NULL, OrgJunitRunnerManipulationSorter *)

FOUNDATION_EXPORT void OrgJunitRunnerManipulationSorter_initWithJavaUtilComparator_(OrgJunitRunnerManipulationSorter *self, id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT OrgJunitRunnerManipulationSorter *new_OrgJunitRunnerManipulationSorter_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitRunnerManipulationSorter *create_OrgJunitRunnerManipulationSorter_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnerManipulationSorter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnerManipulationSorter")
