//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/InternalRenderTheme.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeInternalRenderTheme")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeInternalRenderTheme
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeInternalRenderTheme 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeInternalRenderTheme 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeInternalRenderTheme

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeMapRenderthemeInternalRenderTheme_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeInternalRenderTheme || defined(INCLUDE_OrgMapsforgeMapRenderthemeInternalRenderTheme))
#define OrgMapsforgeMapRenderthemeInternalRenderTheme_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_OrgMapsforgeMapRenderthemeXmlRenderTheme 1
#define INCLUDE_OrgMapsforgeMapRenderthemeXmlRenderTheme 1
#include "org/mapsforge/map/rendertheme/XmlRenderTheme.h"

@class IOSObjectArray;
@class JavaIoInputStream;
@protocol OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback;

typedef NS_ENUM(NSUInteger, OrgMapsforgeMapRenderthemeInternalRenderTheme_Enum) {
  OrgMapsforgeMapRenderthemeInternalRenderTheme_Enum_OSMARENDER = 0,
};

@interface OrgMapsforgeMapRenderthemeInternalRenderTheme : JavaLangEnum < NSCopying, OrgMapsforgeMapRenderthemeXmlRenderTheme >

#pragma mark Public

- (id<OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback>)getMenuCallback;

- (NSString *)getRelativePathPrefix;

- (JavaIoInputStream *)getRenderThemeAsStream;

+ (OrgMapsforgeMapRenderthemeInternalRenderTheme *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapRenderthemeInternalRenderTheme)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeInternalRenderTheme *OrgMapsforgeMapRenderthemeInternalRenderTheme_values_[];

inline OrgMapsforgeMapRenderthemeInternalRenderTheme *OrgMapsforgeMapRenderthemeInternalRenderTheme_get_OSMARENDER();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeMapRenderthemeInternalRenderTheme, OSMARENDER)

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeMapRenderthemeInternalRenderTheme_values();

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeInternalRenderTheme *OrgMapsforgeMapRenderthemeInternalRenderTheme_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeInternalRenderTheme *OrgMapsforgeMapRenderthemeInternalRenderTheme_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeInternalRenderTheme)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeInternalRenderTheme")
