//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/RenderCallback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderCallback")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRenderCallback
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderCallback 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderCallback 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRenderCallback

#if !defined (OrgMapsforgeMapRenderthemeRenderCallback_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderCallback || defined(INCLUDE_OrgMapsforgeMapRenderthemeRenderCallback))
#define OrgMapsforgeMapRenderthemeRenderCallback_

@class OrgMapsforgeCoreGraphicsDisplay;
@class OrgMapsforgeCoreGraphicsPosition;
@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapLayerRendererPolylineContainer;
@class OrgMapsforgeMapReaderPointOfInterest;
@protocol OrgMapsforgeCoreGraphicsBitmap;
@protocol OrgMapsforgeCoreGraphicsPaint;

@protocol OrgMapsforgeMapRenderthemeRenderCallback < JavaObject >

- (void)renderAreaWithOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way
                                  withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)fill
                                  withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)stroke
                                                            withInt:(jint)level;

- (void)renderAreaCaptionWithOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way
                                       withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                                   withInt:(jint)priority
                                                              withNSString:(NSString *)caption
                                                                 withFloat:(jfloat)horizontalOffset
                                                                 withFloat:(jfloat)verticalOffset
                                         withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)fill
                                         withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)stroke
                                      withOrgMapsforgeCoreGraphicsPosition:(OrgMapsforgeCoreGraphicsPosition *)position
                                                                   withInt:(jint)maxTextWidth;

- (void)renderAreaSymbolWithOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way
                                      withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                                  withInt:(jint)priority
                                       withOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)symbol;

- (void)renderPointOfInterestCaptionWithOrgMapsforgeMapReaderPointOfInterest:(OrgMapsforgeMapReaderPointOfInterest *)poi
                                         withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                                     withInt:(jint)priority
                                                                withNSString:(NSString *)caption
                                                                   withFloat:(jfloat)horizontalOffset
                                                                   withFloat:(jfloat)verticalOffset
                                           withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)fill
                                           withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)stroke
                                        withOrgMapsforgeCoreGraphicsPosition:(OrgMapsforgeCoreGraphicsPosition *)position
                                                                     withInt:(jint)maxTextWidth
                                               withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)renderPointOfInterestCircleWithOrgMapsforgeMapReaderPointOfInterest:(OrgMapsforgeMapReaderPointOfInterest *)poi
                                                                  withFloat:(jfloat)radius
                                          withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)fill
                                          withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)stroke
                                                                    withInt:(jint)level
                                              withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)renderPointOfInterestSymbolWithOrgMapsforgeMapReaderPointOfInterest:(OrgMapsforgeMapReaderPointOfInterest *)poi
                                        withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                                    withInt:(jint)priority
                                         withOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)symbol
                                              withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)renderWayWithOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way
                                 withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)stroke
                                                         withFloat:(jfloat)dy
                                                           withInt:(jint)level;

- (void)renderWaySymbolWithOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way
                                     withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                                 withInt:(jint)priority
                                      withOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)symbol
                                                               withFloat:(jfloat)dy
                                                             withBoolean:(jboolean)alignCenter
                                                             withBoolean:(jboolean)repeat
                                                               withFloat:(jfloat)repeatGap
                                                               withFloat:(jfloat)repeatStart
                                                             withBoolean:(jboolean)rotate;

- (void)renderWayTextWithOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way
                                   withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                               withInt:(jint)priority
                                                          withNSString:(NSString *)text
                                                             withFloat:(jfloat)dy
                                     withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)fill
                                     withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)stroke;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRenderCallback)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRenderCallback)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRenderCallback")
