//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/XmlRenderThemeMenuCallback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback

#if !defined (OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback || defined(INCLUDE_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback))
#define OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback_

@class OrgMapsforgeMapRenderthemeXmlRenderThemeStyleMenu;
@protocol JavaUtilSet;

@protocol OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback < JavaObject >

- (id<JavaUtilSet>)getCategoriesWithOrgMapsforgeMapRenderthemeXmlRenderThemeStyleMenu:(OrgMapsforgeMapRenderthemeXmlRenderThemeStyleMenu *)style;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback")
