//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/renderer/CanvasRasterer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererCanvasRasterer")
#ifdef RESTRICT_OrgMapsforgeMapLayerRendererCanvasRasterer
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererCanvasRasterer 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererCanvasRasterer 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerRendererCanvasRasterer

#if !defined (OrgMapsforgeMapLayerRendererCanvasRasterer_) && (INCLUDE_ALL_OrgMapsforgeMapLayerRendererCanvasRasterer || defined(INCLUDE_OrgMapsforgeMapLayerRendererCanvasRasterer))
#define OrgMapsforgeMapLayerRendererCanvasRasterer_

@class OrgMapsforgeCoreGraphicsColor;
@class OrgMapsforgeCoreModelRectangle;
@class OrgMapsforgeCoreModelTile;
@protocol JavaUtilList;
@protocol JavaUtilSet;
@protocol OrgMapsforgeCoreGraphicsBitmap;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;

@interface OrgMapsforgeMapLayerRendererCanvasRasterer : NSObject

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory;

- (void)destroy;

- (void)drawMapElementsWithJavaUtilSet:(id<JavaUtilSet>)elements
         withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)drawWaysWithJavaUtilList:(id<JavaUtilList>)drawWays
   withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)fillWithInt:(jint)color;

- (void)fillOutsideAreasWithOrgMapsforgeCoreGraphicsColor:(OrgMapsforgeCoreGraphicsColor *)color
                       withOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)insideArea;

- (void)fillOutsideAreasWithInt:(jint)color
withOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)insideArea;

- (void)setCanvasBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerRendererCanvasRasterer)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerRendererCanvasRasterer_initWithOrgMapsforgeCoreGraphicsGraphicFactory_(OrgMapsforgeMapLayerRendererCanvasRasterer *self, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory);

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererCanvasRasterer *new_OrgMapsforgeMapLayerRendererCanvasRasterer_initWithOrgMapsforgeCoreGraphicsGraphicFactory_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererCanvasRasterer *create_OrgMapsforgeMapLayerRendererCanvasRasterer_initWithOrgMapsforgeCoreGraphicsGraphicFactory_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerRendererCanvasRasterer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererCanvasRasterer")
