//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/renderer/RendererUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererUtils")
#ifdef RESTRICT_OrgMapsforgeMapLayerRendererRendererUtils
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererUtils 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererUtils 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerRendererRendererUtils

#if !defined (OrgMapsforgeMapLayerRendererRendererUtils_) && (INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererUtils || defined(INCLUDE_OrgMapsforgeMapLayerRendererRendererUtils))
#define OrgMapsforgeMapLayerRendererRendererUtils_

@class IOSObjectArray;

@interface OrgMapsforgeMapLayerRendererRendererUtils : NSObject

#pragma mark Package-Private

+ (IOSObjectArray *)parallelPathWithOrgMapsforgeCoreModelPointArray:(IOSObjectArray *)p
                                                         withDouble:(jdouble)dy;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerRendererRendererUtils)

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeMapLayerRendererRendererUtils_parallelPathWithOrgMapsforgeCoreModelPointArray_withDouble_(IOSObjectArray *p, jdouble dy);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerRendererRendererUtils)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererUtils")
