//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/renderer/RendererJob.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererJob")
#ifdef RESTRICT_OrgMapsforgeMapLayerRendererRendererJob
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererJob 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererJob 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerRendererRendererJob

#if !defined (OrgMapsforgeMapLayerRendererRendererJob_) && (INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererJob || defined(INCLUDE_OrgMapsforgeMapLayerRendererRendererJob))
#define OrgMapsforgeMapLayerRendererRendererJob_

#define RESTRICT_OrgMapsforgeMapLayerQueueJob 1
#define INCLUDE_OrgMapsforgeMapLayerQueueJob 1
#include "org/mapsforge/map/layer/queue/Job.h"

@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapModelDisplayModel;
@class OrgMapsforgeMapRenderthemeRuleRenderThemeFuture;
@protocol OrgMapsforgeMapReaderMapDataStore;

@interface OrgMapsforgeMapLayerRendererRendererJob : OrgMapsforgeMapLayerQueueJob {
 @public
  OrgMapsforgeMapModelDisplayModel *displayModel_;
  jboolean labelsOnly_;
  id<OrgMapsforgeMapReaderMapDataStore> mapDataStore_;
  OrgMapsforgeMapRenderthemeRuleRenderThemeFuture *renderThemeFuture_;
  jfloat textScale_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile
            withOrgMapsforgeMapReaderMapDataStore:(id<OrgMapsforgeMapReaderMapDataStore>)mapFile
withOrgMapsforgeMapRenderthemeRuleRenderThemeFuture:(OrgMapsforgeMapRenderthemeRuleRenderThemeFuture *)renderThemeFuture
             withOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel
                                        withFloat:(jfloat)textScale
                                      withBoolean:(jboolean)isTransparent
                                      withBoolean:(jboolean)labelsOnly;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (OrgMapsforgeMapLayerRendererRendererJob *)otherTileWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)setRetrieveLabelsOnly;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerRendererRendererJob)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerRendererRendererJob, displayModel_, OrgMapsforgeMapModelDisplayModel *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerRendererRendererJob, mapDataStore_, id<OrgMapsforgeMapReaderMapDataStore>)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerRendererRendererJob, renderThemeFuture_, OrgMapsforgeMapRenderthemeRuleRenderThemeFuture *)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerRendererRendererJob_initWithOrgMapsforgeCoreModelTile_withOrgMapsforgeMapReaderMapDataStore_withOrgMapsforgeMapRenderthemeRuleRenderThemeFuture_withOrgMapsforgeMapModelDisplayModel_withFloat_withBoolean_withBoolean_(OrgMapsforgeMapLayerRendererRendererJob *self, OrgMapsforgeCoreModelTile *tile, id<OrgMapsforgeMapReaderMapDataStore> mapFile, OrgMapsforgeMapRenderthemeRuleRenderThemeFuture *renderThemeFuture, OrgMapsforgeMapModelDisplayModel *displayModel, jfloat textScale, jboolean isTransparent, jboolean labelsOnly);

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererRendererJob *new_OrgMapsforgeMapLayerRendererRendererJob_initWithOrgMapsforgeCoreModelTile_withOrgMapsforgeMapReaderMapDataStore_withOrgMapsforgeMapRenderthemeRuleRenderThemeFuture_withOrgMapsforgeMapModelDisplayModel_withFloat_withBoolean_withBoolean_(OrgMapsforgeCoreModelTile *tile, id<OrgMapsforgeMapReaderMapDataStore> mapFile, OrgMapsforgeMapRenderthemeRuleRenderThemeFuture *renderThemeFuture, OrgMapsforgeMapModelDisplayModel *displayModel, jfloat textScale, jboolean isTransparent, jboolean labelsOnly) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererRendererJob *create_OrgMapsforgeMapLayerRendererRendererJob_initWithOrgMapsforgeCoreModelTile_withOrgMapsforgeMapReaderMapDataStore_withOrgMapsforgeMapRenderthemeRuleRenderThemeFuture_withOrgMapsforgeMapModelDisplayModel_withFloat_withBoolean_withBoolean_(OrgMapsforgeCoreModelTile *tile, id<OrgMapsforgeMapReaderMapDataStore> mapFile, OrgMapsforgeMapRenderthemeRuleRenderThemeFuture *renderThemeFuture, OrgMapsforgeMapModelDisplayModel *displayModel, jfloat textScale, jboolean isTransparent, jboolean labelsOnly);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerRendererRendererJob)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererRendererJob")
