//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/renderer/ShapePaintContainer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererShapePaintContainer")
#ifdef RESTRICT_OrgMapsforgeMapLayerRendererShapePaintContainer
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererShapePaintContainer 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerRendererShapePaintContainer 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerRendererShapePaintContainer

#if !defined (OrgMapsforgeMapLayerRendererShapePaintContainer_) && (INCLUDE_ALL_OrgMapsforgeMapLayerRendererShapePaintContainer || defined(INCLUDE_OrgMapsforgeMapLayerRendererShapePaintContainer))
#define OrgMapsforgeMapLayerRendererShapePaintContainer_

@protocol OrgMapsforgeCoreGraphicsPaint;
@protocol OrgMapsforgeMapLayerRendererShapeContainer;

@interface OrgMapsforgeMapLayerRendererShapePaintContainer : NSObject {
 @public
  jfloat dy_;
  id<OrgMapsforgeCoreGraphicsPaint> paint_;
  id<OrgMapsforgeMapLayerRendererShapeContainer> shapeContainer_;
}

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeMapLayerRendererShapeContainer:(id<OrgMapsforgeMapLayerRendererShapeContainer>)shapeContainer
                                 withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (instancetype)initWithOrgMapsforgeMapLayerRendererShapeContainer:(id<OrgMapsforgeMapLayerRendererShapeContainer>)shapeContainer
                                 withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint
                                                         withFloat:(jfloat)dy;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerRendererShapePaintContainer)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerRendererShapePaintContainer, paint_, id<OrgMapsforgeCoreGraphicsPaint>)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerRendererShapePaintContainer, shapeContainer_, id<OrgMapsforgeMapLayerRendererShapeContainer>)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerRendererShapePaintContainer_initWithOrgMapsforgeMapLayerRendererShapeContainer_withOrgMapsforgeCoreGraphicsPaint_(OrgMapsforgeMapLayerRendererShapePaintContainer *self, id<OrgMapsforgeMapLayerRendererShapeContainer> shapeContainer, id<OrgMapsforgeCoreGraphicsPaint> paint);

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererShapePaintContainer *new_OrgMapsforgeMapLayerRendererShapePaintContainer_initWithOrgMapsforgeMapLayerRendererShapeContainer_withOrgMapsforgeCoreGraphicsPaint_(id<OrgMapsforgeMapLayerRendererShapeContainer> shapeContainer, id<OrgMapsforgeCoreGraphicsPaint> paint) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererShapePaintContainer *create_OrgMapsforgeMapLayerRendererShapePaintContainer_initWithOrgMapsforgeMapLayerRendererShapeContainer_withOrgMapsforgeCoreGraphicsPaint_(id<OrgMapsforgeMapLayerRendererShapeContainer> shapeContainer, id<OrgMapsforgeCoreGraphicsPaint> paint);

FOUNDATION_EXPORT void OrgMapsforgeMapLayerRendererShapePaintContainer_initWithOrgMapsforgeMapLayerRendererShapeContainer_withOrgMapsforgeCoreGraphicsPaint_withFloat_(OrgMapsforgeMapLayerRendererShapePaintContainer *self, id<OrgMapsforgeMapLayerRendererShapeContainer> shapeContainer, id<OrgMapsforgeCoreGraphicsPaint> paint, jfloat dy);

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererShapePaintContainer *new_OrgMapsforgeMapLayerRendererShapePaintContainer_initWithOrgMapsforgeMapLayerRendererShapeContainer_withOrgMapsforgeCoreGraphicsPaint_withFloat_(id<OrgMapsforgeMapLayerRendererShapeContainer> shapeContainer, id<OrgMapsforgeCoreGraphicsPaint> paint, jfloat dy) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererShapePaintContainer *create_OrgMapsforgeMapLayerRendererShapePaintContainer_initWithOrgMapsforgeMapLayerRendererShapeContainer_withOrgMapsforgeCoreGraphicsPaint_withFloat_(id<OrgMapsforgeMapLayerRendererShapeContainer> shapeContainer, id<OrgMapsforgeCoreGraphicsPaint> paint, jfloat dy);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerRendererShapePaintContainer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerRendererShapePaintContainer")
