//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/runners/MockitoJUnitRunner.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoRunnersMockitoJUnitRunner")
#ifdef RESTRICT_OrgMockitoRunnersMockitoJUnitRunner
#define INCLUDE_ALL_OrgMockitoRunnersMockitoJUnitRunner 0
#else
#define INCLUDE_ALL_OrgMockitoRunnersMockitoJUnitRunner 1
#endif
#undef RESTRICT_OrgMockitoRunnersMockitoJUnitRunner

#if !defined (OrgMockitoRunnersMockitoJUnitRunner_) && (INCLUDE_ALL_OrgMockitoRunnersMockitoJUnitRunner || defined(INCLUDE_OrgMockitoRunnersMockitoJUnitRunner))
#define OrgMockitoRunnersMockitoJUnitRunner_

#define RESTRICT_OrgJunitRunnerRunner 1
#define INCLUDE_OrgJunitRunnerRunner 1
#include "org/junit/runner/Runner.h"

#define RESTRICT_OrgJunitRunnerManipulationFilterable 1
#define INCLUDE_OrgJunitRunnerManipulationFilterable 1
#include "org/junit/runner/manipulation/Filterable.h"

@class IOSClass;
@class OrgJunitRunnerDescription;
@class OrgJunitRunnerManipulationFilter;
@class OrgJunitRunnerNotificationRunNotifier;

@interface OrgMockitoRunnersMockitoJUnitRunner : OrgJunitRunnerRunner < OrgJunitRunnerManipulationFilterable >

#pragma mark Public

- (instancetype)initWithIOSClass:(IOSClass *)klass;

- (void)filterWithOrgJunitRunnerManipulationFilter:(OrgJunitRunnerManipulationFilter *)filter;

- (OrgJunitRunnerDescription *)getDescription;

- (void)runWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoRunnersMockitoJUnitRunner)

FOUNDATION_EXPORT void OrgMockitoRunnersMockitoJUnitRunner_initWithIOSClass_(OrgMockitoRunnersMockitoJUnitRunner *self, IOSClass *klass);

FOUNDATION_EXPORT OrgMockitoRunnersMockitoJUnitRunner *new_OrgMockitoRunnersMockitoJUnitRunner_initWithIOSClass_(IOSClass *klass) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoRunnersMockitoJUnitRunner *create_OrgMockitoRunnersMockitoJUnitRunner_initWithIOSClass_(IOSClass *klass);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoRunnersMockitoJUnitRunner)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoRunnersMockitoJUnitRunner")
