//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/stubbing/answers/CallsRealMethods.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalStubbingAnswersCallsRealMethods")
#ifdef RESTRICT_OrgMockitoInternalStubbingAnswersCallsRealMethods
#define INCLUDE_ALL_OrgMockitoInternalStubbingAnswersCallsRealMethods 0
#else
#define INCLUDE_ALL_OrgMockitoInternalStubbingAnswersCallsRealMethods 1
#endif
#undef RESTRICT_OrgMockitoInternalStubbingAnswersCallsRealMethods

#if !defined (OrgMockitoInternalStubbingAnswersCallsRealMethods_) && (INCLUDE_ALL_OrgMockitoInternalStubbingAnswersCallsRealMethods || defined(INCLUDE_OrgMockitoInternalStubbingAnswersCallsRealMethods))
#define OrgMockitoInternalStubbingAnswersCallsRealMethods_

#define RESTRICT_OrgMockitoStubbingAnswer 1
#define INCLUDE_OrgMockitoStubbingAnswer 1
#include "org/mockito/stubbing/Answer.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@protocol OrgMockitoInvocationInvocationOnMock;

@interface OrgMockitoInternalStubbingAnswersCallsRealMethods : NSObject < OrgMockitoStubbingAnswer, JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (id)answerWithOrgMockitoInvocationInvocationOnMock:(id<OrgMockitoInvocationInvocationOnMock>)invocation;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalStubbingAnswersCallsRealMethods)

FOUNDATION_EXPORT void OrgMockitoInternalStubbingAnswersCallsRealMethods_init(OrgMockitoInternalStubbingAnswersCallsRealMethods *self);

FOUNDATION_EXPORT OrgMockitoInternalStubbingAnswersCallsRealMethods *new_OrgMockitoInternalStubbingAnswersCallsRealMethods_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalStubbingAnswersCallsRealMethods *create_OrgMockitoInternalStubbingAnswersCallsRealMethods_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalStubbingAnswersCallsRealMethods)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalStubbingAnswersCallsRealMethods")
