//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/configuration/InjectingAnnotationEngine.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalConfigurationInjectingAnnotationEngine")
#ifdef RESTRICT_OrgMockitoInternalConfigurationInjectingAnnotationEngine
#define INCLUDE_ALL_OrgMockitoInternalConfigurationInjectingAnnotationEngine 0
#else
#define INCLUDE_ALL_OrgMockitoInternalConfigurationInjectingAnnotationEngine 1
#endif
#undef RESTRICT_OrgMockitoInternalConfigurationInjectingAnnotationEngine

#if !defined (OrgMockitoInternalConfigurationInjectingAnnotationEngine_) && (INCLUDE_ALL_OrgMockitoInternalConfigurationInjectingAnnotationEngine || defined(INCLUDE_OrgMockitoInternalConfigurationInjectingAnnotationEngine))
#define OrgMockitoInternalConfigurationInjectingAnnotationEngine_

#define RESTRICT_OrgMockitoConfigurationAnnotationEngine 1
#define INCLUDE_OrgMockitoConfigurationAnnotationEngine 1
#include "org/mockito/configuration/AnnotationEngine.h"

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;

@interface OrgMockitoInternalConfigurationInjectingAnnotationEngine : NSObject < OrgMockitoConfigurationAnnotationEngine >

#pragma mark Public

- (instancetype)init;

- (id)createMockForWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation
                           withJavaLangReflectField:(JavaLangReflectField *)field;

- (void)injectMocksWithId:(id)testClassInstance;

- (void)processWithIOSClass:(IOSClass *)clazz
                     withId:(id)testInstance;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalConfigurationInjectingAnnotationEngine)

FOUNDATION_EXPORT void OrgMockitoInternalConfigurationInjectingAnnotationEngine_init(OrgMockitoInternalConfigurationInjectingAnnotationEngine *self);

FOUNDATION_EXPORT OrgMockitoInternalConfigurationInjectingAnnotationEngine *new_OrgMockitoInternalConfigurationInjectingAnnotationEngine_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalConfigurationInjectingAnnotationEngine *create_OrgMockitoInternalConfigurationInjectingAnnotationEngine_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalConfigurationInjectingAnnotationEngine)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalConfigurationInjectingAnnotationEngine")
