//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/AttributeMatcher.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleAttributeMatcher")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleAttributeMatcher
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleAttributeMatcher 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleAttributeMatcher 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleAttributeMatcher

#if !defined (OrgMapsforgeMapRenderthemeRuleAttributeMatcher_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleAttributeMatcher || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleAttributeMatcher))
#define OrgMapsforgeMapRenderthemeRuleAttributeMatcher_

@protocol JavaUtilList;

@protocol OrgMapsforgeMapRenderthemeRuleAttributeMatcher < JavaObject >

- (jboolean)isCoveredByWithOrgMapsforgeMapRenderthemeRuleAttributeMatcher:(id<OrgMapsforgeMapRenderthemeRuleAttributeMatcher>)attributeMatcher;

- (jboolean)matchesWithJavaUtilList:(id<JavaUtilList>)tags;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleAttributeMatcher)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleAttributeMatcher)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleAttributeMatcher")
