//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/Closed.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosed")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleClosed
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosed 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosed 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleClosed

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeMapRenderthemeRuleClosed_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosed || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleClosed))
#define OrgMapsforgeMapRenderthemeRuleClosed_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, OrgMapsforgeMapRenderthemeRuleClosed_Enum) {
  OrgMapsforgeMapRenderthemeRuleClosed_Enum_ANY = 0,
  OrgMapsforgeMapRenderthemeRuleClosed_Enum_NO = 1,
  OrgMapsforgeMapRenderthemeRuleClosed_Enum_YES = 2,
};

@interface OrgMapsforgeMapRenderthemeRuleClosed : JavaLangEnum < NSCopying >

#pragma mark Public

+ (OrgMapsforgeMapRenderthemeRuleClosed *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeMapRenderthemeRuleClosed *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleClosed)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleClosed *OrgMapsforgeMapRenderthemeRuleClosed_values_[];

inline OrgMapsforgeMapRenderthemeRuleClosed *OrgMapsforgeMapRenderthemeRuleClosed_get_ANY();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeMapRenderthemeRuleClosed, ANY)

inline OrgMapsforgeMapRenderthemeRuleClosed *OrgMapsforgeMapRenderthemeRuleClosed_get_NO();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeMapRenderthemeRuleClosed, NO)

inline OrgMapsforgeMapRenderthemeRuleClosed *OrgMapsforgeMapRenderthemeRuleClosed_get_YES();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeMapRenderthemeRuleClosed, YES)

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleClosed *OrgMapsforgeMapRenderthemeRuleClosed_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeMapRenderthemeRuleClosed_values();

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleClosed *OrgMapsforgeMapRenderthemeRuleClosed_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleClosed *OrgMapsforgeMapRenderthemeRuleClosed_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleClosed)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosed")
