//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/ClosedMatcher.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedMatcher")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleClosedMatcher
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedMatcher 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedMatcher 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleClosedMatcher

#if !defined (OrgMapsforgeMapRenderthemeRuleClosedMatcher_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedMatcher || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleClosedMatcher))
#define OrgMapsforgeMapRenderthemeRuleClosedMatcher_

@class OrgMapsforgeMapRenderthemeRuleClosed;

@protocol OrgMapsforgeMapRenderthemeRuleClosedMatcher < JavaObject >

- (jboolean)isCoveredByWithOrgMapsforgeMapRenderthemeRuleClosedMatcher:(id<OrgMapsforgeMapRenderthemeRuleClosedMatcher>)closedMatcher;

- (jboolean)matchesWithOrgMapsforgeMapRenderthemeRuleClosed:(OrgMapsforgeMapRenderthemeRuleClosed *)closed;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleClosedMatcher)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleClosedMatcher)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedMatcher")
