//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/ClosedWayMatcher.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher

#if !defined (OrgMapsforgeMapRenderthemeRuleClosedWayMatcher_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher))
#define OrgMapsforgeMapRenderthemeRuleClosedWayMatcher_

#define RESTRICT_OrgMapsforgeMapRenderthemeRuleClosedMatcher 1
#define INCLUDE_OrgMapsforgeMapRenderthemeRuleClosedMatcher 1
#include "org/mapsforge/map/rendertheme/rule/ClosedMatcher.h"

@class OrgMapsforgeMapRenderthemeRuleClosed;

@interface OrgMapsforgeMapRenderthemeRuleClosedWayMatcher : NSObject < OrgMapsforgeMapRenderthemeRuleClosedMatcher >

#pragma mark Public

- (jboolean)isCoveredByWithOrgMapsforgeMapRenderthemeRuleClosedMatcher:(id<OrgMapsforgeMapRenderthemeRuleClosedMatcher>)closedMatcher;

- (jboolean)matchesWithOrgMapsforgeMapRenderthemeRuleClosed:(OrgMapsforgeMapRenderthemeRuleClosed *)closed;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleClosedWayMatcher)

inline OrgMapsforgeMapRenderthemeRuleClosedWayMatcher *OrgMapsforgeMapRenderthemeRuleClosedWayMatcher_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleClosedWayMatcher *OrgMapsforgeMapRenderthemeRuleClosedWayMatcher_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMapsforgeMapRenderthemeRuleClosedWayMatcher, INSTANCE, OrgMapsforgeMapRenderthemeRuleClosedWayMatcher *)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleClosedWayMatcher)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleClosedWayMatcher")
