//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/ElementNodeMatcher.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher

#if !defined (OrgMapsforgeMapRenderthemeRuleElementNodeMatcher_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher))
#define OrgMapsforgeMapRenderthemeRuleElementNodeMatcher_

#define RESTRICT_OrgMapsforgeMapRenderthemeRuleElementMatcher 1
#define INCLUDE_OrgMapsforgeMapRenderthemeRuleElementMatcher 1
#include "org/mapsforge/map/rendertheme/rule/ElementMatcher.h"

@class OrgMapsforgeMapRenderthemeRuleElement;

@interface OrgMapsforgeMapRenderthemeRuleElementNodeMatcher : NSObject < OrgMapsforgeMapRenderthemeRuleElementMatcher >

#pragma mark Public

- (jboolean)isCoveredByWithOrgMapsforgeMapRenderthemeRuleElementMatcher:(id<OrgMapsforgeMapRenderthemeRuleElementMatcher>)elementMatcher;

- (jboolean)matchesWithOrgMapsforgeMapRenderthemeRuleElement:(OrgMapsforgeMapRenderthemeRuleElement *)element;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleElementNodeMatcher)

inline OrgMapsforgeMapRenderthemeRuleElementNodeMatcher *OrgMapsforgeMapRenderthemeRuleElementNodeMatcher_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleElementNodeMatcher *OrgMapsforgeMapRenderthemeRuleElementNodeMatcher_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMapsforgeMapRenderthemeRuleElementNodeMatcher, INSTANCE, OrgMapsforgeMapRenderthemeRuleElementNodeMatcher *)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleElementNodeMatcher)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementNodeMatcher")
