//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/ElementMatcher.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementMatcher")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleElementMatcher
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementMatcher 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementMatcher 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleElementMatcher

#if !defined (OrgMapsforgeMapRenderthemeRuleElementMatcher_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementMatcher || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleElementMatcher))
#define OrgMapsforgeMapRenderthemeRuleElementMatcher_

@class OrgMapsforgeMapRenderthemeRuleElement;

@protocol OrgMapsforgeMapRenderthemeRuleElementMatcher < JavaObject >

- (jboolean)isCoveredByWithOrgMapsforgeMapRenderthemeRuleElementMatcher:(id<OrgMapsforgeMapRenderthemeRuleElementMatcher>)elementMatcher;

- (jboolean)matchesWithOrgMapsforgeMapRenderthemeRuleElement:(OrgMapsforgeMapRenderthemeRuleElement *)element;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleElementMatcher)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleElementMatcher)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleElementMatcher")
