//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/RenderThemeBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder

#if !defined (OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder))
#define OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_

@class OrgMapsforgeMapRenderthemeRuleRenderTheme;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgXmlpullV1XmlPullParser;

@interface OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder : NSObject {
 @public
  jfloat baseStrokeWidth_;
  jfloat baseTextSize_;
  jboolean hasBackgroundOutside_;
  jint mapBackground_;
  jint mapBackgroundOutside_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory
                                                  withNSString:(NSString *)elementName
                                 withOrgXmlpullV1XmlPullParser:(id<OrgXmlpullV1XmlPullParser>)pullParser;

- (OrgMapsforgeMapRenderthemeRuleRenderTheme *)build;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder)

FOUNDATION_EXPORT void OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withNSString_withOrgXmlpullV1XmlPullParser_(OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder *self, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser);

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder *new_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withNSString_withOrgXmlpullV1XmlPullParser_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder *create_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withNSString_withOrgXmlpullV1XmlPullParser_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, NSString *elementName, id<OrgXmlpullV1XmlPullParser> pullParser);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder")
