//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/rule/RenderTheme.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderTheme")
#ifdef RESTRICT_OrgMapsforgeMapRenderthemeRuleRenderTheme
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderTheme 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderTheme 1
#endif
#undef RESTRICT_OrgMapsforgeMapRenderthemeRuleRenderTheme

#if !defined (OrgMapsforgeMapRenderthemeRuleRenderTheme_) && (INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderTheme || defined(INCLUDE_OrgMapsforgeMapRenderthemeRuleRenderTheme))
#define OrgMapsforgeMapRenderthemeRuleRenderTheme_

@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapLayerRendererPolylineContainer;
@class OrgMapsforgeMapReaderPointOfInterest;
@class OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder;
@class OrgMapsforgeMapRenderthemeRuleRule;
@protocol OrgMapsforgeMapRenderthemeRenderCallback;

@interface OrgMapsforgeMapRenderthemeRuleRenderTheme : NSObject

#pragma mark Public

- (void)destroy;

- (jint)getLevels;

- (jint)getMapBackground;

- (jint)getMapBackgroundOutside;

- (jboolean)hasMapBackgroundOutside;

- (void)incrementRefCount;

- (void)matchClosedWayWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
                 withOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way;

- (void)matchLinearWayWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
                 withOrgMapsforgeMapLayerRendererPolylineContainer:(OrgMapsforgeMapLayerRendererPolylineContainer *)way;

- (void)matchNodeWithOrgMapsforgeMapRenderthemeRenderCallback:(id<OrgMapsforgeMapRenderthemeRenderCallback>)renderCallback
                     withOrgMapsforgeMapReaderPointOfInterest:(OrgMapsforgeMapReaderPointOfInterest *)poi
                                withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)scaleStrokeWidthWithFloat:(jfloat)scaleFactor;

- (void)scaleTextSizeWithFloat:(jfloat)scaleFactor;

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeMapRenderthemeRuleRenderThemeBuilder:(OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder *)renderThemeBuilder;

- (void)addRuleWithOrgMapsforgeMapRenderthemeRuleRule:(OrgMapsforgeMapRenderthemeRuleRule *)rule;

- (void)complete;

- (void)setLevelsWithInt:(jint)levels;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeRuleRenderTheme)

FOUNDATION_EXPORT void OrgMapsforgeMapRenderthemeRuleRenderTheme_initWithOrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_(OrgMapsforgeMapRenderthemeRuleRenderTheme *self, OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder *renderThemeBuilder);

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleRenderTheme *new_OrgMapsforgeMapRenderthemeRuleRenderTheme_initWithOrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_(OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder *renderThemeBuilder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapRenderthemeRuleRenderTheme *create_OrgMapsforgeMapRenderthemeRuleRenderTheme_initWithOrgMapsforgeMapRenderthemeRuleRenderThemeBuilder_(OrgMapsforgeMapRenderthemeRuleRenderThemeBuilder *renderThemeBuilder);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeRuleRenderTheme)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapRenderthemeRuleRenderTheme")
