//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/controller/FrameBufferController.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapControllerFrameBufferController")
#ifdef RESTRICT_OrgMapsforgeMapControllerFrameBufferController
#define INCLUDE_ALL_OrgMapsforgeMapControllerFrameBufferController 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapControllerFrameBufferController 1
#endif
#undef RESTRICT_OrgMapsforgeMapControllerFrameBufferController

#if !defined (OrgMapsforgeMapControllerFrameBufferController_) && (INCLUDE_ALL_OrgMapsforgeMapControllerFrameBufferController || defined(INCLUDE_OrgMapsforgeMapControllerFrameBufferController))
#define OrgMapsforgeMapControllerFrameBufferController_

#define RESTRICT_OrgMapsforgeMapModelCommonObserver 1
#define INCLUDE_OrgMapsforgeMapModelCommonObserver 1
#include "org/mapsforge/map/model/common/Observer.h"

@class OrgMapsforgeMapModelModel;
@class OrgMapsforgeMapViewFrameBuffer;

@interface OrgMapsforgeMapControllerFrameBufferController : NSObject < OrgMapsforgeMapModelCommonObserver >

#pragma mark Public

+ (OrgMapsforgeMapControllerFrameBufferController *)createWithOrgMapsforgeMapViewFrameBuffer:(OrgMapsforgeMapViewFrameBuffer *)frameBuffer
                                                               withOrgMapsforgeMapModelModel:(OrgMapsforgeMapModelModel *)model;

- (void)destroy;

- (void)onChange;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapControllerFrameBufferController)

FOUNDATION_EXPORT OrgMapsforgeMapControllerFrameBufferController *OrgMapsforgeMapControllerFrameBufferController_createWithOrgMapsforgeMapViewFrameBuffer_withOrgMapsforgeMapModelModel_(OrgMapsforgeMapViewFrameBuffer *frameBuffer, OrgMapsforgeMapModelModel *model);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapControllerFrameBufferController)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapControllerFrameBufferController")
