//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/controller/LayerManagerController.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapControllerLayerManagerController")
#ifdef RESTRICT_OrgMapsforgeMapControllerLayerManagerController
#define INCLUDE_ALL_OrgMapsforgeMapControllerLayerManagerController 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapControllerLayerManagerController 1
#endif
#undef RESTRICT_OrgMapsforgeMapControllerLayerManagerController

#if !defined (OrgMapsforgeMapControllerLayerManagerController_) && (INCLUDE_ALL_OrgMapsforgeMapControllerLayerManagerController || defined(INCLUDE_OrgMapsforgeMapControllerLayerManagerController))
#define OrgMapsforgeMapControllerLayerManagerController_

#define RESTRICT_OrgMapsforgeMapModelCommonObserver 1
#define INCLUDE_OrgMapsforgeMapModelCommonObserver 1
#include "org/mapsforge/map/model/common/Observer.h"

@class OrgMapsforgeMapLayerLayerManager;
@class OrgMapsforgeMapModelModel;

@interface OrgMapsforgeMapControllerLayerManagerController : NSObject < OrgMapsforgeMapModelCommonObserver >

#pragma mark Public

+ (OrgMapsforgeMapControllerLayerManagerController *)createWithOrgMapsforgeMapLayerLayerManager:(OrgMapsforgeMapLayerLayerManager *)layerManager
                                                                  withOrgMapsforgeMapModelModel:(OrgMapsforgeMapModelModel *)model;

- (void)onChange;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapControllerLayerManagerController)

FOUNDATION_EXPORT OrgMapsforgeMapControllerLayerManagerController *OrgMapsforgeMapControllerLayerManagerController_createWithOrgMapsforgeMapLayerLayerManager_withOrgMapsforgeMapModelModel_(OrgMapsforgeMapLayerLayerManager *layerManager, OrgMapsforgeMapModelModel *model);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapControllerLayerManagerController)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapControllerLayerManagerController")
