//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/controller/MapViewController.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapControllerMapViewController")
#ifdef RESTRICT_OrgMapsforgeMapControllerMapViewController
#define INCLUDE_ALL_OrgMapsforgeMapControllerMapViewController 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapControllerMapViewController 1
#endif
#undef RESTRICT_OrgMapsforgeMapControllerMapViewController

#if !defined (OrgMapsforgeMapControllerMapViewController_) && (INCLUDE_ALL_OrgMapsforgeMapControllerMapViewController || defined(INCLUDE_OrgMapsforgeMapControllerMapViewController))
#define OrgMapsforgeMapControllerMapViewController_

#define RESTRICT_OrgMapsforgeMapModelCommonObserver 1
#define INCLUDE_OrgMapsforgeMapModelCommonObserver 1
#include "org/mapsforge/map/model/common/Observer.h"

@class OrgMapsforgeMapModelModel;
@protocol OrgMapsforgeMapViewMapView;

@interface OrgMapsforgeMapControllerMapViewController : NSObject < OrgMapsforgeMapModelCommonObserver >

#pragma mark Public

+ (OrgMapsforgeMapControllerMapViewController *)createWithOrgMapsforgeMapViewMapView:(id<OrgMapsforgeMapViewMapView>)mapView
                                                       withOrgMapsforgeMapModelModel:(OrgMapsforgeMapModelModel *)model;

- (void)onChange;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapControllerMapViewController)

FOUNDATION_EXPORT OrgMapsforgeMapControllerMapViewController *OrgMapsforgeMapControllerMapViewController_createWithOrgMapsforgeMapViewMapView_withOrgMapsforgeMapModelModel_(id<OrgMapsforgeMapViewMapView> mapView, OrgMapsforgeMapModelModel *model);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapControllerMapViewController)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapControllerMapViewController")
