//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/MapPosition.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition")
#ifdef RESTRICT_OrgMapsforgeCoreModelMapPosition
#define INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelMapPosition

#if !defined (OrgMapsforgeCoreModelMapPosition_) && (INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition || defined(INCLUDE_OrgMapsforgeCoreModelMapPosition))
#define OrgMapsforgeCoreModelMapPosition_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class OrgMapsforgeCoreModelLatLong;

@interface OrgMapsforgeCoreModelMapPosition : NSObject < JavaIoSerializable > {
 @public
  OrgMapsforgeCoreModelLatLong *latLong_;
  jbyte zoomLevel_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)latLong
                                            withByte:(jbyte)zoomLevel;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelMapPosition)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelMapPosition, latLong_, OrgMapsforgeCoreModelLatLong *)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withByte_(OrgMapsforgeCoreModelMapPosition *self, OrgMapsforgeCoreModelLatLong *latLong, jbyte zoomLevel);

FOUNDATION_EXPORT OrgMapsforgeCoreModelMapPosition *new_OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withByte_(OrgMapsforgeCoreModelLatLong *latLong, jbyte zoomLevel) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelMapPosition *create_OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withByte_(OrgMapsforgeCoreModelLatLong *latLong, jbyte zoomLevel);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelMapPosition)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition")
