//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/Point.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelPoint")
#ifdef RESTRICT_OrgMapsforgeCoreModelPoint
#define INCLUDE_ALL_OrgMapsforgeCoreModelPoint 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelPoint 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelPoint

#if !defined (OrgMapsforgeCoreModelPoint_) && (INCLUDE_ALL_OrgMapsforgeCoreModelPoint || defined(INCLUDE_OrgMapsforgeCoreModelPoint))
#define OrgMapsforgeCoreModelPoint_

#define RESTRICT_JavaLangComparable 1
#define INCLUDE_JavaLangComparable 1
#include "java/lang/Comparable.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@interface OrgMapsforgeCoreModelPoint : NSObject < JavaLangComparable, JavaIoSerializable > {
 @public
  jdouble x_;
  jdouble y_;
}

#pragma mark Public

- (instancetype)initWithDouble:(jdouble)x
                    withDouble:(jdouble)y;

- (jint)compareToWithId:(OrgMapsforgeCoreModelPoint *)point;

- (jdouble)distanceWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)point;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (OrgMapsforgeCoreModelPoint *)offsetWithDouble:(jdouble)dx
                                      withDouble:(jdouble)dy;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelPoint)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelPoint_initWithDouble_withDouble_(OrgMapsforgeCoreModelPoint *self, jdouble x, jdouble y);

FOUNDATION_EXPORT OrgMapsforgeCoreModelPoint *new_OrgMapsforgeCoreModelPoint_initWithDouble_withDouble_(jdouble x, jdouble y) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelPoint *create_OrgMapsforgeCoreModelPoint_initWithDouble_withDouble_(jdouble x, jdouble y);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelPoint)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelPoint")
