//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/queue/JobQueue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerQueueJobQueue")
#ifdef RESTRICT_OrgMapsforgeMapLayerQueueJobQueue
#define INCLUDE_ALL_OrgMapsforgeMapLayerQueueJobQueue 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerQueueJobQueue 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerQueueJobQueue

#if !defined (OrgMapsforgeMapLayerQueueJobQueue_) && (INCLUDE_ALL_OrgMapsforgeMapLayerQueueJobQueue || defined(INCLUDE_OrgMapsforgeMapLayerQueueJobQueue))
#define OrgMapsforgeMapLayerQueueJobQueue_

@class OrgMapsforgeMapLayerQueueJob;
@class OrgMapsforgeMapModelDisplayModel;
@class OrgMapsforgeMapModelMapViewPosition;

@interface OrgMapsforgeMapLayerQueueJobQueue : NSObject

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapModelMapViewPosition:(OrgMapsforgeMapModelMapViewPosition *)mapViewPosition
                       withOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel;

- (void)addWithOrgMapsforgeMapLayerQueueJob:(OrgMapsforgeMapLayerQueueJob *)job;

- (OrgMapsforgeMapLayerQueueJob *)get;

- (void)notifyWorkers;

- (void)removeWithOrgMapsforgeMapLayerQueueJob:(OrgMapsforgeMapLayerQueueJob *)job;

- (jint)size;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerQueueJobQueue)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerQueueJobQueue_initWithOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeMapModelDisplayModel_(OrgMapsforgeMapLayerQueueJobQueue *self, OrgMapsforgeMapModelMapViewPosition *mapViewPosition, OrgMapsforgeMapModelDisplayModel *displayModel);

FOUNDATION_EXPORT OrgMapsforgeMapLayerQueueJobQueue *new_OrgMapsforgeMapLayerQueueJobQueue_initWithOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeMapModelDisplayModel_(OrgMapsforgeMapModelMapViewPosition *mapViewPosition, OrgMapsforgeMapModelDisplayModel *displayModel) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapLayerQueueJobQueue *create_OrgMapsforgeMapLayerQueueJobQueue_initWithOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeMapModelDisplayModel_(OrgMapsforgeMapModelMapViewPosition *mapViewPosition, OrgMapsforgeMapModelDisplayModel *displayModel);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerQueueJobQueue)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerQueueJobQueue")
