//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/Deserializer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderDeserializer")
#ifdef RESTRICT_OrgMapsforgeMapReaderDeserializer
#define INCLUDE_ALL_OrgMapsforgeMapReaderDeserializer 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderDeserializer 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderDeserializer

#if !defined (OrgMapsforgeMapReaderDeserializer_) && (INCLUDE_ALL_OrgMapsforgeMapReaderDeserializer || defined(INCLUDE_OrgMapsforgeMapReaderDeserializer))
#define OrgMapsforgeMapReaderDeserializer_

@class IOSByteArray;

@interface OrgMapsforgeMapReaderDeserializer : NSObject

#pragma mark Package-Private

+ (jlong)getFiveBytesLongWithByteArray:(IOSByteArray *)buffer
                               withInt:(jint)offset;

+ (jint)getIntWithByteArray:(IOSByteArray *)buffer
                    withInt:(jint)offset;

+ (jlong)getLongWithByteArray:(IOSByteArray *)buffer
                      withInt:(jint)offset;

+ (jint)getShortWithByteArray:(IOSByteArray *)buffer
                      withInt:(jint)offset;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderDeserializer)

FOUNDATION_EXPORT jlong OrgMapsforgeMapReaderDeserializer_getFiveBytesLongWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

FOUNDATION_EXPORT jint OrgMapsforgeMapReaderDeserializer_getIntWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

FOUNDATION_EXPORT jlong OrgMapsforgeMapReaderDeserializer_getLongWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

FOUNDATION_EXPORT jint OrgMapsforgeMapReaderDeserializer_getShortWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderDeserializer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderDeserializer")
