//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/IndexCacheEntryKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderIndexCacheEntryKey")
#ifdef RESTRICT_OrgMapsforgeMapReaderIndexCacheEntryKey
#define INCLUDE_ALL_OrgMapsforgeMapReaderIndexCacheEntryKey 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderIndexCacheEntryKey 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderIndexCacheEntryKey

#if !defined (OrgMapsforgeMapReaderIndexCacheEntryKey_) && (INCLUDE_ALL_OrgMapsforgeMapReaderIndexCacheEntryKey || defined(INCLUDE_OrgMapsforgeMapReaderIndexCacheEntryKey))
#define OrgMapsforgeMapReaderIndexCacheEntryKey_

@class OrgMapsforgeMapReaderHeaderSubFileParameter;

@interface OrgMapsforgeMapReaderIndexCacheEntryKey : NSObject

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeMapReaderHeaderSubFileParameter:(OrgMapsforgeMapReaderHeaderSubFileParameter *)subFileParameter
                                                           withLong:(jlong)indexBlockNumber;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderIndexCacheEntryKey)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderIndexCacheEntryKey_initWithOrgMapsforgeMapReaderHeaderSubFileParameter_withLong_(OrgMapsforgeMapReaderIndexCacheEntryKey *self, OrgMapsforgeMapReaderHeaderSubFileParameter *subFileParameter, jlong indexBlockNumber);

FOUNDATION_EXPORT OrgMapsforgeMapReaderIndexCacheEntryKey *new_OrgMapsforgeMapReaderIndexCacheEntryKey_initWithOrgMapsforgeMapReaderHeaderSubFileParameter_withLong_(OrgMapsforgeMapReaderHeaderSubFileParameter *subFileParameter, jlong indexBlockNumber) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderIndexCacheEntryKey *create_OrgMapsforgeMapReaderIndexCacheEntryKey_initWithOrgMapsforgeMapReaderHeaderSubFileParameter_withLong_(OrgMapsforgeMapReaderHeaderSubFileParameter *subFileParameter, jlong indexBlockNumber);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderIndexCacheEntryKey)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderIndexCacheEntryKey")
