//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/MapDataStore.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderMapDataStore")
#ifdef RESTRICT_OrgMapsforgeMapReaderMapDataStore
#define INCLUDE_ALL_OrgMapsforgeMapReaderMapDataStore 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderMapDataStore 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderMapDataStore

#if !defined (OrgMapsforgeMapReaderMapDataStore_) && (INCLUDE_ALL_OrgMapsforgeMapReaderMapDataStore || defined(INCLUDE_OrgMapsforgeMapReaderMapDataStore))
#define OrgMapsforgeMapReaderMapDataStore_

@class JavaLangByte;
@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelLatLong;
@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapReaderMapReadResult;

@protocol OrgMapsforgeMapReaderMapDataStore < JavaObject >

- (OrgMapsforgeCoreModelBoundingBox *)boundingBox;

- (void)close;

- (jlong)getDataTimestampWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (OrgMapsforgeCoreModelLatLong *)startPosition;

- (JavaLangByte *)startZoomLevel;

- (OrgMapsforgeMapReaderMapReadResult *)readMapDataWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (jboolean)supportsTileWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderMapDataStore)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderMapDataStore)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderMapDataStore")
