//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/MapReadResultBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderMapReadResultBuilder")
#ifdef RESTRICT_OrgMapsforgeMapReaderMapReadResultBuilder
#define INCLUDE_ALL_OrgMapsforgeMapReaderMapReadResultBuilder 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderMapReadResultBuilder 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderMapReadResultBuilder

#if !defined (OrgMapsforgeMapReaderMapReadResultBuilder_) && (INCLUDE_ALL_OrgMapsforgeMapReaderMapReadResultBuilder || defined(INCLUDE_OrgMapsforgeMapReaderMapReadResultBuilder))
#define OrgMapsforgeMapReaderMapReadResultBuilder_

@class OrgMapsforgeMapReaderMapReadResult;
@class OrgMapsforgeMapReaderPoiWayBundle;
@protocol JavaUtilList;

@interface OrgMapsforgeMapReaderMapReadResultBuilder : NSObject {
 @public
  jboolean isWater_;
  id<JavaUtilList> pointOfInterests_;
  id<JavaUtilList> ways_;
}

#pragma mark Package-Private

- (instancetype)init;

- (void)addWithOrgMapsforgeMapReaderPoiWayBundle:(OrgMapsforgeMapReaderPoiWayBundle *)poiWayBundle;

- (OrgMapsforgeMapReaderMapReadResult *)build;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderMapReadResultBuilder)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderMapReadResultBuilder, pointOfInterests_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderMapReadResultBuilder, ways_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderMapReadResultBuilder_init(OrgMapsforgeMapReaderMapReadResultBuilder *self);

FOUNDATION_EXPORT OrgMapsforgeMapReaderMapReadResultBuilder *new_OrgMapsforgeMapReaderMapReadResultBuilder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderMapReadResultBuilder *create_OrgMapsforgeMapReaderMapReadResultBuilder_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderMapReadResultBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderMapReadResultBuilder")
