//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/PoiWayBundle.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderPoiWayBundle")
#ifdef RESTRICT_OrgMapsforgeMapReaderPoiWayBundle
#define INCLUDE_ALL_OrgMapsforgeMapReaderPoiWayBundle 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderPoiWayBundle 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderPoiWayBundle

#if !defined (OrgMapsforgeMapReaderPoiWayBundle_) && (INCLUDE_ALL_OrgMapsforgeMapReaderPoiWayBundle || defined(INCLUDE_OrgMapsforgeMapReaderPoiWayBundle))
#define OrgMapsforgeMapReaderPoiWayBundle_

@protocol JavaUtilList;

@interface OrgMapsforgeMapReaderPoiWayBundle : NSObject {
 @public
  id<JavaUtilList> pois_;
  id<JavaUtilList> ways_;
}

#pragma mark Package-Private

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)pois
                    withJavaUtilList:(id<JavaUtilList>)ways;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderPoiWayBundle)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderPoiWayBundle, pois_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderPoiWayBundle, ways_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderPoiWayBundle_initWithJavaUtilList_withJavaUtilList_(OrgMapsforgeMapReaderPoiWayBundle *self, id<JavaUtilList> pois, id<JavaUtilList> ways);

FOUNDATION_EXPORT OrgMapsforgeMapReaderPoiWayBundle *new_OrgMapsforgeMapReaderPoiWayBundle_initWithJavaUtilList_withJavaUtilList_(id<JavaUtilList> pois, id<JavaUtilList> ways) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderPoiWayBundle *create_OrgMapsforgeMapReaderPoiWayBundle_initWithJavaUtilList_withJavaUtilList_(id<JavaUtilList> pois, id<JavaUtilList> ways);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderPoiWayBundle)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderPoiWayBundle")
