//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/QueryParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderQueryParameters")
#ifdef RESTRICT_OrgMapsforgeMapReaderQueryParameters
#define INCLUDE_ALL_OrgMapsforgeMapReaderQueryParameters 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderQueryParameters 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderQueryParameters

#if !defined (OrgMapsforgeMapReaderQueryParameters_) && (INCLUDE_ALL_OrgMapsforgeMapReaderQueryParameters || defined(INCLUDE_OrgMapsforgeMapReaderQueryParameters))
#define OrgMapsforgeMapReaderQueryParameters_

@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapReaderHeaderSubFileParameter;

@interface OrgMapsforgeMapReaderQueryParameters : NSObject {
 @public
  jlong fromBaseTileX_;
  jlong fromBaseTileY_;
  jlong fromBlockX_;
  jlong fromBlockY_;
  jint queryTileBitmask_;
  jint queryZoomLevel_;
  jlong toBaseTileX_;
  jlong toBaseTileY_;
  jlong toBlockX_;
  jlong toBlockY_;
  jboolean useTileBitmask_;
}

#pragma mark Public

- (void)calculateBaseTilesWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile
        withOrgMapsforgeMapReaderHeaderSubFileParameter:(OrgMapsforgeMapReaderHeaderSubFileParameter *)subFileParameter;

- (void)calculateBlocksWithOrgMapsforgeMapReaderHeaderSubFileParameter:(OrgMapsforgeMapReaderHeaderSubFileParameter *)subFileParameter;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderQueryParameters)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderQueryParameters_init(OrgMapsforgeMapReaderQueryParameters *self);

FOUNDATION_EXPORT OrgMapsforgeMapReaderQueryParameters *new_OrgMapsforgeMapReaderQueryParameters_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderQueryParameters *create_OrgMapsforgeMapReaderQueryParameters_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderQueryParameters)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderQueryParameters")
