//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/ReadBuffer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderReadBuffer")
#ifdef RESTRICT_OrgMapsforgeMapReaderReadBuffer
#define INCLUDE_ALL_OrgMapsforgeMapReaderReadBuffer 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderReadBuffer 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderReadBuffer

#if !defined (OrgMapsforgeMapReaderReadBuffer_) && (INCLUDE_ALL_OrgMapsforgeMapReaderReadBuffer || defined(INCLUDE_OrgMapsforgeMapReaderReadBuffer))
#define OrgMapsforgeMapReaderReadBuffer_

@class JavaIoRandomAccessFile;

@interface OrgMapsforgeMapReaderReadBuffer : NSObject

#pragma mark Public

- (jbyte)readByte;

- (jboolean)readFromFileWithInt:(jint)length;

- (jint)readInt;

- (jlong)readLong;

- (jint)readShort;

- (jint)readSignedInt;

- (jint)readUnsignedInt;

- (NSString *)readUTF8EncodedString;

- (NSString *)readUTF8EncodedStringWithInt:(jint)stringLength;

#pragma mark Package-Private

- (instancetype)initWithJavaIoRandomAccessFile:(JavaIoRandomAccessFile *)inputFile;

- (jint)getBufferPosition;

- (jint)getBufferSize;

- (void)setBufferPositionWithInt:(jint)bufferPosition;

- (void)skipBytesWithInt:(jint)bytes;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapReaderReadBuffer)

inline jint OrgMapsforgeMapReaderReadBuffer_get_MAXIMUM_BUFFER_SIZE();
#define OrgMapsforgeMapReaderReadBuffer_MAXIMUM_BUFFER_SIZE 2500000
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeMapReaderReadBuffer, MAXIMUM_BUFFER_SIZE, jint)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderReadBuffer_initWithJavaIoRandomAccessFile_(OrgMapsforgeMapReaderReadBuffer *self, JavaIoRandomAccessFile *inputFile);

FOUNDATION_EXPORT OrgMapsforgeMapReaderReadBuffer *new_OrgMapsforgeMapReaderReadBuffer_initWithJavaIoRandomAccessFile_(JavaIoRandomAccessFile *inputFile) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderReadBuffer *create_OrgMapsforgeMapReaderReadBuffer_initWithJavaIoRandomAccessFile_(JavaIoRandomAccessFile *inputFile);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderReadBuffer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderReadBuffer")
