//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/Way.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapReaderWay")
#ifdef RESTRICT_OrgMapsforgeMapReaderWay
#define INCLUDE_ALL_OrgMapsforgeMapReaderWay 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapReaderWay 1
#endif
#undef RESTRICT_OrgMapsforgeMapReaderWay

#if !defined (OrgMapsforgeMapReaderWay_) && (INCLUDE_ALL_OrgMapsforgeMapReaderWay || defined(INCLUDE_OrgMapsforgeMapReaderWay))
#define OrgMapsforgeMapReaderWay_

@class IOSObjectArray;
@class OrgMapsforgeCoreModelLatLong;
@protocol JavaUtilList;

@interface OrgMapsforgeMapReaderWay : NSObject {
 @public
  OrgMapsforgeCoreModelLatLong *labelPosition_;
  IOSObjectArray *latLongs_;
  jbyte layer_;
  id<JavaUtilList> tags_;
}

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

#pragma mark Package-Private

- (instancetype)initWithByte:(jbyte)layer
            withJavaUtilList:(id<JavaUtilList>)tags
withOrgMapsforgeCoreModelLatLongArray2:(IOSObjectArray *)latLongs
withOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)labelPosition;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderWay)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderWay, labelPosition_, OrgMapsforgeCoreModelLatLong *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderWay, latLongs_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderWay, tags_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderWay_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLongArray2_withOrgMapsforgeCoreModelLatLong_(OrgMapsforgeMapReaderWay *self, jbyte layer, id<JavaUtilList> tags, IOSObjectArray *latLongs, OrgMapsforgeCoreModelLatLong *labelPosition);

FOUNDATION_EXPORT OrgMapsforgeMapReaderWay *new_OrgMapsforgeMapReaderWay_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLongArray2_withOrgMapsforgeCoreModelLatLong_(jbyte layer, id<JavaUtilList> tags, IOSObjectArray *latLongs, OrgMapsforgeCoreModelLatLong *labelPosition) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapReaderWay *create_OrgMapsforgeMapReaderWay_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLongArray2_withOrgMapsforgeCoreModelLatLong_(jbyte layer, id<JavaUtilList> tags, IOSObjectArray *latLongs, OrgMapsforgeCoreModelLatLong *labelPosition);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderWay)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapReaderWay")
