//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/model/common/Observable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapModelCommonObservable")
#ifdef RESTRICT_OrgMapsforgeMapModelCommonObservable
#define INCLUDE_ALL_OrgMapsforgeMapModelCommonObservable 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapModelCommonObservable 1
#endif
#undef RESTRICT_OrgMapsforgeMapModelCommonObservable

#if !defined (OrgMapsforgeMapModelCommonObservable_) && (INCLUDE_ALL_OrgMapsforgeMapModelCommonObservable || defined(INCLUDE_OrgMapsforgeMapModelCommonObservable))
#define OrgMapsforgeMapModelCommonObservable_

@protocol OrgMapsforgeMapModelCommonObserver;

@interface OrgMapsforgeMapModelCommonObservable : NSObject

#pragma mark Public

- (void)addObserverWithOrgMapsforgeMapModelCommonObserver:(id<OrgMapsforgeMapModelCommonObserver>)observer;

- (void)removeObserverWithOrgMapsforgeMapModelCommonObserver:(id<OrgMapsforgeMapModelCommonObserver>)observer;

#pragma mark Protected

- (instancetype)init;

- (void)notifyObservers;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapModelCommonObservable)

FOUNDATION_EXPORT void OrgMapsforgeMapModelCommonObservable_init(OrgMapsforgeMapModelCommonObservable *self);

FOUNDATION_EXPORT OrgMapsforgeMapModelCommonObservable *new_OrgMapsforgeMapModelCommonObservable_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapModelCommonObservable *create_OrgMapsforgeMapModelCommonObservable_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapModelCommonObservable)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapModelCommonObservable")
