//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/model/common/Observer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapModelCommonObserver")
#ifdef RESTRICT_OrgMapsforgeMapModelCommonObserver
#define INCLUDE_ALL_OrgMapsforgeMapModelCommonObserver 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapModelCommonObserver 1
#endif
#undef RESTRICT_OrgMapsforgeMapModelCommonObserver

#if !defined (OrgMapsforgeMapModelCommonObserver_) && (INCLUDE_ALL_OrgMapsforgeMapModelCommonObserver || defined(INCLUDE_OrgMapsforgeMapModelCommonObserver))
#define OrgMapsforgeMapModelCommonObserver_

@protocol OrgMapsforgeMapModelCommonObserver < JavaObject >

- (void)onChange;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapModelCommonObserver)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapModelCommonObserver)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapModelCommonObserver")
