//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/model/FrameBufferModel.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapModelFrameBufferModel")
#ifdef RESTRICT_OrgMapsforgeMapModelFrameBufferModel
#define INCLUDE_ALL_OrgMapsforgeMapModelFrameBufferModel 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapModelFrameBufferModel 1
#endif
#undef RESTRICT_OrgMapsforgeMapModelFrameBufferModel

#if !defined (OrgMapsforgeMapModelFrameBufferModel_) && (INCLUDE_ALL_OrgMapsforgeMapModelFrameBufferModel || defined(INCLUDE_OrgMapsforgeMapModelFrameBufferModel))
#define OrgMapsforgeMapModelFrameBufferModel_

#define RESTRICT_OrgMapsforgeMapModelCommonObservable 1
#define INCLUDE_OrgMapsforgeMapModelCommonObservable 1
#include "org/mapsforge/map/model/common/Observable.h"

@class OrgMapsforgeCoreModelDimension;
@class OrgMapsforgeCoreModelMapPosition;

@interface OrgMapsforgeMapModelFrameBufferModel : OrgMapsforgeMapModelCommonObservable

#pragma mark Public

- (instancetype)init;

- (OrgMapsforgeCoreModelDimension *)getDimension;

- (OrgMapsforgeCoreModelMapPosition *)getMapPosition;

- (jdouble)getOverdrawFactor;

- (void)setDimensionWithOrgMapsforgeCoreModelDimension:(OrgMapsforgeCoreModelDimension *)dimension;

- (void)setMapPositionWithOrgMapsforgeCoreModelMapPosition:(OrgMapsforgeCoreModelMapPosition *)mapPosition;

- (void)setOverdrawFactorWithDouble:(jdouble)overdrawFactor;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapModelFrameBufferModel)

FOUNDATION_EXPORT void OrgMapsforgeMapModelFrameBufferModel_init(OrgMapsforgeMapModelFrameBufferModel *self);

FOUNDATION_EXPORT OrgMapsforgeMapModelFrameBufferModel *new_OrgMapsforgeMapModelFrameBufferModel_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapModelFrameBufferModel *create_OrgMapsforgeMapModelFrameBufferModel_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapModelFrameBufferModel)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapModelFrameBufferModel")
