//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/model/MapViewPosition.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapModelMapViewPosition")
#ifdef RESTRICT_OrgMapsforgeMapModelMapViewPosition
#define INCLUDE_ALL_OrgMapsforgeMapModelMapViewPosition 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapModelMapViewPosition 1
#endif
#undef RESTRICT_OrgMapsforgeMapModelMapViewPosition

#if !defined (OrgMapsforgeMapModelMapViewPosition_) && (INCLUDE_ALL_OrgMapsforgeMapModelMapViewPosition || defined(INCLUDE_OrgMapsforgeMapModelMapViewPosition))
#define OrgMapsforgeMapModelMapViewPosition_

#define RESTRICT_OrgMapsforgeMapModelCommonObservable 1
#define INCLUDE_OrgMapsforgeMapModelCommonObservable 1
#include "org/mapsforge/map/model/common/Observable.h"

#define RESTRICT_OrgMapsforgeMapModelCommonPersistable 1
#define INCLUDE_OrgMapsforgeMapModelCommonPersistable 1
#include "org/mapsforge/map/model/common/Persistable.h"

@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelLatLong;
@class OrgMapsforgeCoreModelMapPosition;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeMapModelDisplayModel;
@protocol OrgMapsforgeMapModelCommonPreferencesFacade;

@interface OrgMapsforgeMapModelMapViewPosition : OrgMapsforgeMapModelCommonObservable < OrgMapsforgeMapModelCommonPersistable >

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapModelDisplayModel:(OrgMapsforgeMapModelDisplayModel *)displayModel;

- (void)animateToWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)pos;

- (jboolean)animationInProgress;

- (void)destroy;

- (OrgMapsforgeCoreModelLatLong *)getCenter;

- (OrgMapsforgeCoreModelBoundingBox *)getMapLimit;

- (OrgMapsforgeCoreModelMapPosition *)getMapPosition;

- (OrgMapsforgeCoreModelLatLong *)getPivot;

- (OrgMapsforgeCoreModelPoint *)getPivotXYWithByte:(jbyte)zoomLevel;

- (jdouble)getScaleFactor;

- (jbyte)getZoomLevel;

- (jbyte)getZoomLevelMax;

- (jbyte)getZoomLevelMin;

- (void)init__WithOrgMapsforgeMapModelCommonPreferencesFacade:(id<OrgMapsforgeMapModelCommonPreferencesFacade>)preferencesFacade OBJC_METHOD_FAMILY_NONE;

- (void)moveCenterWithDouble:(jdouble)moveHorizontal
                  withDouble:(jdouble)moveVertical;

- (void)moveCenterAndZoomWithDouble:(jdouble)moveHorizontal
                         withDouble:(jdouble)moveVertical
                           withByte:(jbyte)zoomLevelDiff;

- (void)saveWithOrgMapsforgeMapModelCommonPreferencesFacade:(id<OrgMapsforgeMapModelCommonPreferencesFacade>)preferencesFacade;

- (void)setCenterWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)latLong;

- (void)setMapLimitWithOrgMapsforgeCoreModelBoundingBox:(OrgMapsforgeCoreModelBoundingBox *)mapLimit;

- (void)setMapPositionWithOrgMapsforgeCoreModelMapPosition:(OrgMapsforgeCoreModelMapPosition *)mapPosition;

- (void)setPivotWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)pivot;

- (void)setScaleFactorWithDouble:(jdouble)scaleFactor;

- (void)setScaleFactorAdjustmentWithDouble:(jdouble)adjustment;

- (void)setZoomLevelWithByte:(jbyte)zoomLevel;

- (void)setZoomLevelMaxWithByte:(jbyte)zoomLevelMax;

- (void)setZoomLevelMinWithByte:(jbyte)zoomLevelMin;

- (void)zoomWithByte:(jbyte)zoomLevelDiff;

- (void)zoomIn;

- (void)zoomOut;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapModelMapViewPosition)

FOUNDATION_EXPORT void OrgMapsforgeMapModelMapViewPosition_initWithOrgMapsforgeMapModelDisplayModel_(OrgMapsforgeMapModelMapViewPosition *self, OrgMapsforgeMapModelDisplayModel *displayModel);

FOUNDATION_EXPORT OrgMapsforgeMapModelMapViewPosition *new_OrgMapsforgeMapModelMapViewPosition_initWithOrgMapsforgeMapModelDisplayModel_(OrgMapsforgeMapModelDisplayModel *displayModel) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapModelMapViewPosition *create_OrgMapsforgeMapModelMapViewPosition_initWithOrgMapsforgeMapModelDisplayModel_(OrgMapsforgeMapModelDisplayModel *displayModel);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapModelMapViewPosition)

#endif

#if !defined (OrgMapsforgeMapModelMapViewPosition_ZoomAnimator_) && (INCLUDE_ALL_OrgMapsforgeMapModelMapViewPosition || defined(INCLUDE_OrgMapsforgeMapModelMapViewPosition_ZoomAnimator))
#define OrgMapsforgeMapModelMapViewPosition_ZoomAnimator_

#define RESTRICT_OrgMapsforgeMapUtilPausableThread 1
#define INCLUDE_OrgMapsforgeMapUtilPausableThread 1
#include "org/mapsforge/map/util/PausableThread.h"

@class OrgMapsforgeMapModelMapViewPosition;
@class OrgMapsforgeMapUtilPausableThread_ThreadPriority;

@interface OrgMapsforgeMapModelMapViewPosition_ZoomAnimator : OrgMapsforgeMapUtilPausableThread {
 @public
  jdouble scaleDifference_;
  jdouble startScaleFactor_;
}

#pragma mark Protected

- (void)doWork;

- (OrgMapsforgeMapUtilPausableThread_ThreadPriority *)getThreadPriority;

- (jboolean)hasWork;

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeMapModelMapViewPosition:(OrgMapsforgeMapModelMapViewPosition *)outer$;

- (void)startAnimationWithDouble:(jdouble)startScaleFactor
                      withDouble:(jdouble)targetScaleFactor;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapModelMapViewPosition_ZoomAnimator)

FOUNDATION_EXPORT void OrgMapsforgeMapModelMapViewPosition_ZoomAnimator_initWithOrgMapsforgeMapModelMapViewPosition_(OrgMapsforgeMapModelMapViewPosition_ZoomAnimator *self, OrgMapsforgeMapModelMapViewPosition *outer$);

FOUNDATION_EXPORT OrgMapsforgeMapModelMapViewPosition_ZoomAnimator *new_OrgMapsforgeMapModelMapViewPosition_ZoomAnimator_initWithOrgMapsforgeMapModelMapViewPosition_(OrgMapsforgeMapModelMapViewPosition *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeMapModelMapViewPosition_ZoomAnimator *create_OrgMapsforgeMapModelMapViewPosition_ZoomAnimator_initWithOrgMapsforgeMapModelMapViewPosition_(OrgMapsforgeMapModelMapViewPosition *outer$);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapModelMapViewPosition_ZoomAnimator)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapModelMapViewPosition")
