//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/listeners/MockingProgressListener.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener")
#ifdef RESTRICT_OrgMockitoInternalListenersMockingProgressListener
#define INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener 0
#else
#define INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener 1
#endif
#undef RESTRICT_OrgMockitoInternalListenersMockingProgressListener

#if !defined (OrgMockitoInternalListenersMockingProgressListener_) && (INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener || defined(INCLUDE_OrgMockitoInternalListenersMockingProgressListener))
#define OrgMockitoInternalListenersMockingProgressListener_

@protocol OrgMockitoInternalListenersMockingProgressListener < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalListenersMockingProgressListener)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalListenersMockingProgressListener)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener")
