//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/util/MockitoSpy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalUtilMockitoSpy")
#ifdef RESTRICT_OrgMockitoInternalUtilMockitoSpy
#define INCLUDE_ALL_OrgMockitoInternalUtilMockitoSpy 0
#else
#define INCLUDE_ALL_OrgMockitoInternalUtilMockitoSpy 1
#endif
#undef RESTRICT_OrgMockitoInternalUtilMockitoSpy

#if !defined (OrgMockitoInternalUtilMockitoSpy_) && (INCLUDE_ALL_OrgMockitoInternalUtilMockitoSpy || defined(INCLUDE_OrgMockitoInternalUtilMockitoSpy))
#define OrgMockitoInternalUtilMockitoSpy_

@protocol OrgMockitoInternalUtilMockitoSpy < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalUtilMockitoSpy)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalUtilMockitoSpy)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalUtilMockitoSpy")
