//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/junit/BeforeClass.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitBeforeClass")
#ifdef RESTRICT_OrgJunitBeforeClass
#define INCLUDE_ALL_OrgJunitBeforeClass 0
#else
#define INCLUDE_ALL_OrgJunitBeforeClass 1
#endif
#undef RESTRICT_OrgJunitBeforeClass

#if !defined (OrgJunitBeforeClass_) && (INCLUDE_ALL_OrgJunitBeforeClass || defined(INCLUDE_OrgJunitBeforeClass))
#define OrgJunitBeforeClass_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol OrgJunitBeforeClass < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitBeforeClass : NSObject < OrgJunitBeforeClass >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitBeforeClass)

FOUNDATION_EXPORT id<OrgJunitBeforeClass> create_OrgJunitBeforeClass();

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitBeforeClass)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitBeforeClass")
