//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ugos/j2objc-master/junit/build_result/java/org/junit/Rule.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRule")
#ifdef RESTRICT_OrgJunitRule
#define INCLUDE_ALL_OrgJunitRule 0
#else
#define INCLUDE_ALL_OrgJunitRule 1
#endif
#undef RESTRICT_OrgJunitRule

#if !defined (OrgJunitRule_) && (INCLUDE_ALL_OrgJunitRule || defined(INCLUDE_OrgJunitRule))
#define OrgJunitRule_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol OrgJunitRule < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitRule : NSObject < OrgJunitRule >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRule)

FOUNDATION_EXPORT id<OrgJunitRule> create_OrgJunitRule();

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRule)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRule")
