//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Align.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsAlign
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsAlign

#if !defined (OrgMapsforgeCoreGraphicsAlign_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign || defined(INCLUDE_OrgMapsforgeCoreGraphicsAlign))
#define OrgMapsforgeCoreGraphicsAlign_

@interface OrgMapsforgeCoreGraphicsAlign : NSObject

#pragma mark Public

- (instancetype)init;

- (OrgMapsforgeCoreGraphicsAlign *)fromStringWithNSString:(NSString *)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsAlign)

inline OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_get_CENTER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_CENTER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMapsforgeCoreGraphicsAlign, CENTER, OrgMapsforgeCoreGraphicsAlign *)

inline OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_get_LEFT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_LEFT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMapsforgeCoreGraphicsAlign, LEFT, OrgMapsforgeCoreGraphicsAlign *)

inline OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_get_RIGHT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_RIGHT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMapsforgeCoreGraphicsAlign, RIGHT, OrgMapsforgeCoreGraphicsAlign *)

FOUNDATION_EXPORT void OrgMapsforgeCoreGraphicsAlign_init(OrgMapsforgeCoreGraphicsAlign *self);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *new_OrgMapsforgeCoreGraphicsAlign_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *create_OrgMapsforgeCoreGraphicsAlign_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsAlign)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign")
