//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Paint.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsPaint
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsPaint

#if !defined (OrgMapsforgeCoreGraphicsPaint_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint || defined(INCLUDE_OrgMapsforgeCoreGraphicsPaint))
#define OrgMapsforgeCoreGraphicsPaint_

@class IOSFloatArray;
@class OrgMapsforgeCoreGraphicsAlign;
@class OrgMapsforgeCoreGraphicsCap;
@class OrgMapsforgeCoreGraphicsColor;
@class OrgMapsforgeCoreGraphicsFontFamily;
@class OrgMapsforgeCoreGraphicsFontStyle;
@class OrgMapsforgeCoreGraphicsJoin;
@class OrgMapsforgeCoreGraphicsStyle;
@class OrgMapsforgeCoreModelPoint;
@protocol OrgMapsforgeCoreGraphicsBitmap;

@protocol OrgMapsforgeCoreGraphicsPaint < JavaObject >

- (jint)getTextHeightWithNSString:(NSString *)text;

- (jint)getTextWidthWithNSString:(NSString *)text;

- (jboolean)isTransparent;

- (void)setBitmapShaderWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap;

- (void)setBitmapShaderShiftWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)origin;

- (void)setColorWithOrgMapsforgeCoreGraphicsColor:(OrgMapsforgeCoreGraphicsColor *)color;

- (void)setColorWithInt:(jint)color;

- (void)setDashPathEffectWithFloatArray:(IOSFloatArray *)strokeDasharray;

- (void)setStrokeCapWithOrgMapsforgeCoreGraphicsCap:(OrgMapsforgeCoreGraphicsCap *)cap;

- (void)setStrokeJoinWithOrgMapsforgeCoreGraphicsJoin:(OrgMapsforgeCoreGraphicsJoin *)join;

- (void)setStrokeWidthWithFloat:(jfloat)strokeWidth;

- (void)setStyleWithOrgMapsforgeCoreGraphicsStyle:(OrgMapsforgeCoreGraphicsStyle *)style;

- (void)setTextAlignWithOrgMapsforgeCoreGraphicsAlign:(OrgMapsforgeCoreGraphicsAlign *)align;

- (void)setTextSizeWithFloat:(jfloat)textSize;

- (void)setTypefaceWithOrgMapsforgeCoreGraphicsFontFamily:(OrgMapsforgeCoreGraphicsFontFamily *)fontFamily
                    withOrgMapsforgeCoreGraphicsFontStyle:(OrgMapsforgeCoreGraphicsFontStyle *)fontStyle;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsPaint)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsPaint)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint")
