//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Position.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsPosition
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsPosition

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsPosition_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition || defined(INCLUDE_OrgMapsforgeCoreGraphicsPosition))
#define OrgMapsforgeCoreGraphicsPosition_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, OrgMapsforgeCoreGraphicsPosition_Enum) {
  OrgMapsforgeCoreGraphicsPosition_Enum_AUTO = 0,
  OrgMapsforgeCoreGraphicsPosition_Enum_CENTER = 1,
  OrgMapsforgeCoreGraphicsPosition_Enum_BELOW = 2,
  OrgMapsforgeCoreGraphicsPosition_Enum_BELOW_LEFT = 3,
  OrgMapsforgeCoreGraphicsPosition_Enum_BELOW_RIGHT = 4,
  OrgMapsforgeCoreGraphicsPosition_Enum_ABOVE = 5,
  OrgMapsforgeCoreGraphicsPosition_Enum_ABOVE_LEFT = 6,
  OrgMapsforgeCoreGraphicsPosition_Enum_ABOVE_RIGHT = 7,
  OrgMapsforgeCoreGraphicsPosition_Enum_LEFT = 8,
  OrgMapsforgeCoreGraphicsPosition_Enum_RIGHT = 9,
};

@interface OrgMapsforgeCoreGraphicsPosition : JavaLangEnum < NSCopying >

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsPosition *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsPosition *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsPosition)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_values_[];

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_AUTO();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, AUTO)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_CENTER();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, CENTER)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_BELOW();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, BELOW)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_BELOW_LEFT();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, BELOW_LEFT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_BELOW_RIGHT();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, BELOW_RIGHT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_ABOVE();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, ABOVE)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_ABOVE_LEFT();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, ABOVE_LEFT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_ABOVE_RIGHT();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, ABOVE_RIGHT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_LEFT();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, LEFT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_RIGHT();
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, RIGHT)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsPosition_values();

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsPosition)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition")
