//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/labels/LabelStore.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapLayerLabelsLabelStore")
#ifdef RESTRICT_OrgMapsforgeMapLayerLabelsLabelStore
#define INCLUDE_ALL_OrgMapsforgeMapLayerLabelsLabelStore 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapLayerLabelsLabelStore 1
#endif
#undef RESTRICT_OrgMapsforgeMapLayerLabelsLabelStore

#if !defined (OrgMapsforgeMapLayerLabelsLabelStore_) && (INCLUDE_ALL_OrgMapsforgeMapLayerLabelsLabelStore || defined(INCLUDE_OrgMapsforgeMapLayerLabelsLabelStore))
#define OrgMapsforgeMapLayerLabelsLabelStore_

@protocol JavaUtilList;
@protocol JavaUtilSet;

@protocol OrgMapsforgeMapLayerLabelsLabelStore < JavaObject >

- (void)clear;

- (jint)getVersion;

- (id<JavaUtilList>)getVisibleItemsWithJavaUtilSet:(id<JavaUtilSet>)tiles;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerLabelsLabelStore)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerLabelsLabelStore)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapLayerLabelsLabelStore")
