//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/view/MapView.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeMapViewMapView")
#ifdef RESTRICT_OrgMapsforgeMapViewMapView
#define INCLUDE_ALL_OrgMapsforgeMapViewMapView 0
#else
#define INCLUDE_ALL_OrgMapsforgeMapViewMapView 1
#endif
#undef RESTRICT_OrgMapsforgeMapViewMapView

#if !defined (OrgMapsforgeMapViewMapView_) && (INCLUDE_ALL_OrgMapsforgeMapViewMapView || defined(INCLUDE_OrgMapsforgeMapViewMapView))
#define OrgMapsforgeMapViewMapView_

@class OrgMapsforgeCoreModelDimension;
@class OrgMapsforgeMapLayerLayerManager;
@class OrgMapsforgeMapModelModel;
@class OrgMapsforgeMapScalebarMapScaleBar;
@class OrgMapsforgeMapViewFpsCounter;
@class OrgMapsforgeMapViewFrameBuffer;

@protocol OrgMapsforgeMapViewMapView < JavaObject >

- (void)destroy;

- (OrgMapsforgeCoreModelDimension *)getDimension;

- (OrgMapsforgeMapViewFpsCounter *)getFpsCounter;

- (OrgMapsforgeMapScalebarMapScaleBar *)getMapScaleBar;

- (void)setMapScaleBarWithOrgMapsforgeMapScalebarMapScaleBar:(OrgMapsforgeMapScalebarMapScaleBar *)mapScaleBar;

- (OrgMapsforgeMapViewFrameBuffer *)getFrameBuffer;

- (jint)getHeight;

- (OrgMapsforgeMapLayerLayerManager *)getLayerManager;

- (OrgMapsforgeMapModelModel *)getModel;

- (jint)getWidth;

- (void)repaint;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapViewMapView)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapViewMapView)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeMapViewMapView")
